CREATE UNIQUE INDEX "ApiUsageRecord_pkey" ON public."ApiUsageRecord" USING btree (id);
CREATE INDEX "ApiUsageRecord_provider_idx" ON public."ApiUsageRecord" USING btree (provider);
CREATE INDEX "ApiUsageRecord_responseStatus_idx" ON public."ApiUsageRecord" USING btree ("responseStatus");
CREATE INDEX "ApiUsageRecord_responseStatus_serviceType_createdAt_idx" ON public."ApiUsageRecord" USING btree ("responseStatus", "serviceType", "createdAt");
CREATE INDEX "ApiUsageRecord_serviceType_idx" ON public."ApiUsageRecord" USING btree ("serviceType");
CREATE INDEX "ApiUsageRecord_userId_createdAt_idx" ON public."ApiUsageRecord" USING btree ("userId", "createdAt");
CREATE UNIQUE INDEX "BioAuthGroup_groupId_key" ON public."BioAuthGroup" USING btree ("groupId");
CREATE UNIQUE INDEX "BioAuthGroup_pkey" ON public."BioAuthGroup" USING btree (id);
CREATE INDEX "BioAuthGroup_userId_createdAt_idx" ON public."BioAuthGroup" USING btree ("userId", "createdAt");
CREATE UNIQUE INDEX "CreditAccount_pkey" ON public."CreditAccount" USING btree (id);
CREATE UNIQUE INDEX "CreditAccount_userId_key" ON public."CreditAccount" USING btree ("userId");
CREATE UNIQUE INDEX "CreditAnomalyRecord_accountId_dayStart_key" ON public."CreditAnomalyRecord" USING btree ("accountId", "dayStart");
CREATE INDEX "CreditAnomalyRecord_dayStart_severity_idx" ON public."CreditAnomalyRecord" USING btree ("dayStart", severity);
CREATE UNIQUE INDEX "CreditAnomalyRecord_pkey" ON public."CreditAnomalyRecord" USING btree (id);
CREATE INDEX "CreditAnomalyRecord_severity_totalAmount_idx" ON public."CreditAnomalyRecord" USING btree (severity, "totalAmount");
CREATE INDEX "CreditAnomalyRecord_userId_dayStart_idx" ON public."CreditAnomalyRecord" USING btree ("userId", "dayStart");
CREATE UNIQUE INDEX "CreditConsumePolicy_code_key" ON public."CreditConsumePolicy" USING btree (code);
CREATE UNIQUE INDEX "CreditConsumePolicy_pkey" ON public."CreditConsumePolicy" USING btree (id);
CREATE INDEX "CreditConsumePolicy_scopeType_scopeValue_isActive_idx" ON public."CreditConsumePolicy" USING btree ("scopeType", "scopeValue", "isActive");
CREATE INDEX "CreditLot_accountId_status_expiresAt_idx" ON public."CreditLot" USING btree ("accountId", status, "expiresAt");
CREATE INDEX "CreditLot_accountId_validityType_status_idx" ON public."CreditLot" USING btree ("accountId", "validityType", status);
CREATE INDEX "CreditLot_orderId_idx" ON public."CreditLot" USING btree ("orderId");
CREATE UNIQUE INDEX "CreditLot_pkey" ON public."CreditLot" USING btree (id);
CREATE INDEX "CreditLot_scopeType_scopeValue_status_idx" ON public."CreditLot" USING btree ("scopeType", "scopeValue", status);
CREATE INDEX "CreditLot_subscriptionId_idx" ON public."CreditLot" USING btree ("subscriptionId");
CREATE UNIQUE INDEX "CreditPackage_pkey" ON public."CreditPackage" USING btree (id);
CREATE UNIQUE INDEX "CreditPricing_pkey" ON public."CreditPricing" USING btree (id);
CREATE UNIQUE INDEX "CreditPricing_serviceType_key" ON public."CreditPricing" USING btree ("serviceType");
CREATE INDEX "CreditTransaction_accountId_createdAt_idx" ON public."CreditTransaction" USING btree ("accountId", "createdAt");
CREATE INDEX "CreditTransaction_businessType_createdAt_idx" ON public."CreditTransaction" USING btree ("businessType", "createdAt");
CREATE INDEX "CreditTransaction_creditLotId_createdAt_idx" ON public."CreditTransaction" USING btree ("creditLotId", "createdAt");
CREATE INDEX "CreditTransaction_expiresAt_isExpired_idx" ON public."CreditTransaction" USING btree ("expiresAt", "isExpired");
CREATE INDEX "CreditTransaction_membershipPlanId_createdAt_idx" ON public."CreditTransaction" USING btree ("membershipPlanId", "createdAt");
CREATE UNIQUE INDEX "CreditTransaction_pkey" ON public."CreditTransaction" USING btree (id);
CREATE INDEX "CreditTransaction_subscriptionId_createdAt_idx" ON public."CreditTransaction" USING btree ("subscriptionId", "createdAt");
CREATE INDEX "CreditTransaction_type_idx" ON public."CreditTransaction" USING btree (type);
CREATE UNIQUE INDEX "GlobalImageHistory_pkey" ON public."GlobalImageHistory" USING btree (id);
CREATE INDEX "GlobalImageHistory_sourceType_idx" ON public."GlobalImageHistory" USING btree ("sourceType");
CREATE INDEX "GlobalImageHistory_userId_createdAt_idx" ON public."GlobalImageHistory" USING btree ("userId", "createdAt" DESC);
CREATE INDEX "GlobalImageHistory_userId_sourceProjectId_createdAt_idx" ON public."GlobalImageHistory" USING btree ("userId", "sourceProjectId", "createdAt" DESC);
CREATE INDEX "ImageTask_nodeId_idx" ON public."ImageTask" USING btree ("nodeId");
CREATE UNIQUE INDEX "ImageTask_pkey" ON public."ImageTask" USING btree (id);
CREATE INDEX "ImageTask_status_createdAt_idx" ON public."ImageTask" USING btree (status, "createdAt");
CREATE INDEX "ImageTask_userId_createdAt_idx" ON public."ImageTask" USING btree ("userId", "createdAt");
CREATE UNIQUE INDEX "InvitationCode_code_key" ON public."InvitationCode" USING btree (code);
CREATE UNIQUE INDEX "InvitationCode_pkey" ON public."InvitationCode" USING btree (id);
CREATE INDEX "InvitationCode_status_idx" ON public."InvitationCode" USING btree (status);
CREATE INDEX "InvitationRedemption_codeId_idx" ON public."InvitationRedemption" USING btree ("codeId");
CREATE INDEX "InvitationRedemption_inviteeUserId_idx" ON public."InvitationRedemption" USING btree ("inviteeUserId");
CREATE INDEX "InvitationRedemption_inviterUserId_idx" ON public."InvitationRedemption" USING btree ("inviterUserId");
CREATE UNIQUE INDEX "InvitationRedemption_pkey" ON public."InvitationRedemption" USING btree (id);
CREATE UNIQUE INDEX "MembershipEntitlementSnapshot_pkey" ON public."MembershipEntitlementSnapshot" USING btree ("userId");
CREATE UNIQUE INDEX "MembershipPlan_code_key" ON public."MembershipPlan" USING btree (code);
CREATE INDEX "MembershipPlan_isActive_sortOrder_idx" ON public."MembershipPlan" USING btree ("isActive", "sortOrder");
CREATE UNIQUE INDEX "MembershipPlan_pkey" ON public."MembershipPlan" USING btree (id);
CREATE INDEX "MembershipSubscriptionChange_currentSubscriptionId_status_idx" ON public."MembershipSubscriptionChange" USING btree ("currentSubscriptionId", status);
CREATE UNIQUE INDEX "MembershipSubscriptionChange_pkey" ON public."MembershipSubscriptionChange" USING btree (id);
CREATE INDEX "MembershipSubscriptionChange_targetPlanId_status_idx" ON public."MembershipSubscriptionChange" USING btree ("targetPlanId", status);
CREATE INDEX "MembershipSubscriptionChange_userId_status_effectiveAt_idx" ON public."MembershipSubscriptionChange" USING btree ("userId", status, "effectiveAt");
CREATE INDEX "NodeConfig_category_sortOrder_idx" ON public."NodeConfig" USING btree (category, "sortOrder");
CREATE UNIQUE INDEX "NodeConfig_nodeKey_key" ON public."NodeConfig" USING btree ("nodeKey");
CREATE UNIQUE INDEX "NodeConfig_pkey" ON public."NodeConfig" USING btree (id);
CREATE INDEX "NodeConfig_status_idx" ON public."NodeConfig" USING btree (status);
CREATE INDEX "PaymentOrder_orderNo_idx" ON public."PaymentOrder" USING btree ("orderNo");
CREATE UNIQUE INDEX "PaymentOrder_orderNo_key" ON public."PaymentOrder" USING btree ("orderNo");
CREATE INDEX "PaymentOrder_orderType_status_idx" ON public."PaymentOrder" USING btree ("orderType", status);
CREATE UNIQUE INDEX "PaymentOrder_pkey" ON public."PaymentOrder" USING btree (id);
CREATE INDEX "PaymentOrder_status_idx" ON public."PaymentOrder" USING btree (status);
CREATE INDEX "PaymentOrder_userId_createdAt_idx" ON public."PaymentOrder" USING btree ("userId", "createdAt");
CREATE INDEX "Project_createdAt_idx" ON public."Project" USING btree ("createdAt");
CREATE UNIQUE INDEX "Project_pkey" ON public."Project" USING btree (id);
CREATE INDEX "Project_userId_createdAt_idx" ON public."Project" USING btree ("userId", "createdAt");
CREATE INDEX "Project_userId_updatedAt_idx" ON public."Project" USING btree ("userId", "updatedAt");
CREATE UNIQUE INDEX "ProviderTestJob_pkey" ON public."ProviderTestJob" USING btree (id);
CREATE INDEX "ProviderTestJob_runId_idx" ON public."ProviderTestJob" USING btree ("runId");
CREATE INDEX "ProviderTestJob_status_submittedAt_idx" ON public."ProviderTestJob" USING btree (status, "submittedAt");
CREATE UNIQUE INDEX "ProviderTestLog_pkey" ON public."ProviderTestLog" USING btree (id);
CREATE INDEX "ProviderTestLog_providerName_createdAt_idx" ON public."ProviderTestLog" USING btree ("providerName", "createdAt");
CREATE INDEX "ProviderTestLog_status_createdAt_idx" ON public."ProviderTestLog" USING btree (status, "createdAt");
CREATE UNIQUE INDEX "ProviderTestRun_pkey" ON public."ProviderTestRun" USING btree (id);
CREATE INDEX "ProviderTestRun_status_startedAt_idx" ON public."ProviderTestRun" USING btree (status, "startedAt");
CREATE UNIQUE INDEX "PublicTemplate_pkey" ON public."PublicTemplate" USING btree (id);
CREATE INDEX idx_publictemplate_category ON public."PublicTemplate" USING btree (category);
CREATE INDEX idx_publictemplate_thumbnailsmall ON public."PublicTemplate" USING btree ("thumbnailSmall");
CREATE INDEX "RefreshToken_expiresAt_idx" ON public."RefreshToken" USING btree ("expiresAt");
CREATE UNIQUE INDEX "RefreshToken_pkey" ON public."RefreshToken" USING btree (id);
CREATE INDEX "RefreshToken_userId_expiresAt_isRevoked_idx" ON public."RefreshToken" USING btree ("userId", "expiresAt", "isRevoked");
CREATE INDEX "RefreshToken_userId_isRevoked_idx" ON public."RefreshToken" USING btree ("userId", "isRevoked");
CREATE UNIQUE INDEX "SystemSetting_key_key" ON public."SystemSetting" USING btree (key);
CREATE UNIQUE INDEX "SystemSetting_pkey" ON public."SystemSetting" USING btree (id);
CREATE UNIQUE INDEX "Team_one_personal_per_owner" ON public."Team" USING btree ("ownerId") WHERE ("isPersonal" = true);
CREATE INDEX "Team_ownerId_isPersonal_idx" ON public."Team" USING btree ("ownerId", "isPersonal");
CREATE UNIQUE INDEX "Team_pkey" ON public."Team" USING btree (id);
CREATE UNIQUE INDEX "TeamCreditAccount_pkey" ON public."TeamCreditAccount" USING btree (id);
CREATE UNIQUE INDEX "TeamCreditAccount_teamId_key" ON public."TeamCreditAccount" USING btree ("teamId");
CREATE INDEX "TeamCreditLedger_entryType_reserveExpiresAt_idx" ON public."TeamCreditLedger" USING btree ("entryType", "reserveExpiresAt");
CREATE UNIQUE INDEX "TeamCreditLedger_pkey" ON public."TeamCreditLedger" USING btree (id);
CREATE UNIQUE INDEX "TeamCreditLedger_teamAccId_entryType_null_taskId_key" ON public."TeamCreditLedger" USING btree ("teamAccId", "entryType") WHERE ("taskId" IS NULL);
CREATE UNIQUE INDEX "TeamCreditLedger_teamAccId_entryType_taskId_key" ON public."TeamCreditLedger" USING btree ("teamAccId", "entryType", "taskId") WHERE ("taskId" IS NOT NULL);
CREATE UNIQUE INDEX "TeamCreditLot_pkey" ON public."TeamCreditLot" USING btree (id);
CREATE INDEX "TeamCreditLot_teamCreditAccId_expiresAt_idx" ON public."TeamCreditLot" USING btree ("teamCreditAccId", "expiresAt");
CREATE UNIQUE INDEX "TeamInvite_code_key" ON public."TeamInvite" USING btree (code);
CREATE UNIQUE INDEX "TeamInvite_pkey" ON public."TeamInvite" USING btree (id);
CREATE INDEX "TeamInvite_teamId_status_idx" ON public."TeamInvite" USING btree ("teamId", status);
CREATE UNIQUE INDEX "TeamMembership_pkey" ON public."TeamMembership" USING btree ("teamId", "userId");
CREATE INDEX "TeamMembership_userId_idx" ON public."TeamMembership" USING btree ("userId");
CREATE UNIQUE INDEX "TeamProjectShare_pkey" ON public."TeamProjectShare" USING btree ("projectId", "teamId");
CREATE INDEX "TeamProjectShare_teamId_idx" ON public."TeamProjectShare" USING btree ("teamId");
CREATE UNIQUE INDEX "TeamSeatPackage_paymentOrderId_key" ON public."TeamSeatPackage" USING btree ("paymentOrderId");
CREATE UNIQUE INDEX "TeamSeatPackage_pkey" ON public."TeamSeatPackage" USING btree (id);
CREATE INDEX "TeamSeatPackage_teamId_status_expiresAt_idx" ON public."TeamSeatPackage" USING btree ("teamId", status, "expiresAt");
CREATE INDEX "TeamSubscription_nextCreditRenewalAt_status_idx" ON public."TeamSubscription" USING btree ("nextCreditRenewalAt", status);
CREATE UNIQUE INDEX "TeamSubscription_one_active_per_team" ON public."TeamSubscription" USING btree ("teamId") WHERE (status = 'active'::text);
CREATE UNIQUE INDEX "TeamSubscription_pkey" ON public."TeamSubscription" USING btree (id);
CREATE INDEX "TeamSubscription_teamId_status_idx" ON public."TeamSubscription" USING btree ("teamId", status);
CREATE UNIQUE INDEX "TeamSubscriptionPlan_pkey" ON public."TeamSubscriptionPlan" USING btree (id);
CREATE UNIQUE INDEX "User_email_key" ON public."User" USING btree (email);
CREATE INDEX "User_email_status_idx" ON public."User" USING btree (email, status);
CREATE UNIQUE INDEX "User_phone_key" ON public."User" USING btree (phone);
CREATE INDEX "User_phone_status_idx" ON public."User" USING btree (phone, status);
CREATE UNIQUE INDEX "User_pkey" ON public."User" USING btree (id);
CREATE INDEX "User_role_status_idx" ON public."User" USING btree (role, status);
CREATE UNIQUE INDEX "User_watchaUserId_key" ON public."User" USING btree ("watchaUserId");
CREATE UNIQUE INDEX "User_wechatOfficialOpenId_key" ON public."User" USING btree ("wechatOfficialOpenId");
CREATE INDEX "User_wechatUnionId_idx" ON public."User" USING btree ("wechatUnionId");
CREATE UNIQUE INDEX "User_wechatUnionId_key" ON public."User" USING btree ("wechatUnionId");
CREATE INDEX "UserMembershipSubscription_currentPeriodEndAt_status_idx" ON public."UserMembershipSubscription" USING btree ("currentPeriodEndAt", status);
CREATE INDEX "UserMembershipSubscription_membershipPlanId_status_idx" ON public."UserMembershipSubscription" USING btree ("membershipPlanId", status);
CREATE UNIQUE INDEX "UserMembershipSubscription_pkey" ON public."UserMembershipSubscription" USING btree (id);
CREATE INDEX "UserMembershipSubscription_userId_status_idx" ON public."UserMembershipSubscription" USING btree ("userId", status);
CREATE UNIQUE INDEX "UserTemplate_pkey" ON public."UserTemplate" USING btree (id);
CREATE INDEX "UserTemplate_userId_createdAt_idx" ON public."UserTemplate" USING btree ("userId", "createdAt" DESC);
CREATE INDEX "UserTemplate_userId_updatedAt_idx" ON public."UserTemplate" USING btree ("userId", "updatedAt" DESC);
CREATE INDEX "VideoTask_nodeId_idx" ON public."VideoTask" USING btree ("nodeId");
CREATE UNIQUE INDEX "VideoTask_pkey" ON public."VideoTask" USING btree (id);
CREATE INDEX "VideoTask_status_updatedAt_idx" ON public."VideoTask" USING btree (status, "updatedAt");
CREATE INDEX "VideoTask_userId_createdAt_idx" ON public."VideoTask" USING btree ("userId", "createdAt");
CREATE INDEX "WechatLoginSession_openId_idx" ON public."WechatLoginSession" USING btree ("openId");
CREATE UNIQUE INDEX "WechatLoginSession_pkey" ON public."WechatLoginSession" USING btree (id);
CREATE UNIQUE INDEX "WechatLoginSession_sceneKey_key" ON public."WechatLoginSession" USING btree ("sceneKey");
CREATE INDEX "WechatLoginSession_status_expiresAt_idx" ON public."WechatLoginSession" USING btree (status, "expiresAt");
CREATE INDEX "WechatLoginSession_userId_createdAt_idx" ON public."WechatLoginSession" USING btree ("userId", "createdAt" DESC);
CREATE UNIQUE INDEX "WorkflowHistory_pkey" ON public."WorkflowHistory" USING btree ("userId", "projectId", "updatedAt");
CREATE INDEX "WorkflowHistory_updatedAt_idx" ON public."WorkflowHistory" USING btree ("updatedAt");
CREATE UNIQUE INDEX "WorkflowHistory_userId_projectId_version_key" ON public."WorkflowHistory" USING btree ("userId", "projectId", version);
CREATE UNIQUE INDEX _prisma_migrations_pkey ON public._prisma_migrations USING btree (id);