-- 002-seedance-face-param-pricing-and-gpt54-ratio.sql
-- Purpose:
--   1. Change Seedance face variants from misleading flat fixed prices to
--      param-priced base values that are 10% above their same-name base models.
--   2. Correct gpt-5.4 input ModelRatio to 1x.
--
-- Notes:
--   Param pricing itself is generated by model/pricing.go from model params and
--   linearVideoPricingRules. The ModelPrice values here are direct/fallback base
--   values used by pricing summaries and clients that do not select a spec.
--
-- Scope: PostgreSQL (new-api DB), data-only, idempotent.
-- After applying: restart new-api or clear pricing cache.

\set ON_ERROR_STOP on

BEGIN;

-- Base fallback values:
--   doubao-seedance-2.0      = 20  -> face = 22
--   doubao-seedance-2.0-fast = 15  -> fast-face = 16.5
UPDATE options
SET value = (
  COALESCE(NULLIF(value, '')::jsonb, '{}'::jsonb)
  || '{
    "doubao-seedance-2.0-face": 22,
    "doubao-seedance-2.0-face-apimart": 22,
    "doubao-seedance-2.0-fast-face": 16.5,
    "doubao-seedance-2.0-fast-face-apimart": 16.5
  }'::jsonb
)::text
WHERE key = 'ModelPrice';

UPDATE options
SET value = (
  COALESCE(NULLIF(value, '')::jsonb, '{}'::jsonb)
  || '{"gpt-5.4": 1.0}'::jsonb
)::text
WHERE key = 'ModelRatio';

\echo
\echo '----- corrected Seedance face ModelPrice + gpt-5.4 ModelRatio -----'
SELECT
  key,
  value::jsonb -> 'doubao-seedance-2.0-face' AS seedance_face,
  value::jsonb -> 'doubao-seedance-2.0-fast-face' AS seedance_fast_face,
  value::jsonb -> 'gpt-5.4' AS gpt_54
FROM options
WHERE key IN ('ModelPrice', 'ModelRatio')
ORDER BY key;

COMMIT;
