import { randomUUID } from 'node:crypto';
import { ConstructionStore, ensureProject, identifier, finite, positive, round } from './construction-model.mjs';

const text = (value, label, max = 200) => { if (typeof value !== 'string' || !value.trim()) throw new Error(`${label} 不能为空`); return value.trim().slice(0, max); };
const money = (value, label) => round(positive(value, label), 2);
const rows = (value, label) => { if (!Array.isArray(value) || !value.length) throw new Error(`${label} 不能为空`); if (value.length > 20_000) throw new Error(`${label} 数量过多`); return value; };
const isoDate = (value, label) => { const date = value == null ? new Date() : new Date(value); if (Number.isNaN(date.getTime())) throw new Error(`${label} 必须是有效日期`); return date.toISOString(); };
const uniqueIds = (items, field, label) => { const seen = new Set(); for (const item of items) { const id = item[field]; if (seen.has(id)) throw new Error(`${label} 存在重复：${id}`); seen.add(id); } };
const deliveryEntries = (state, orderId, lineId) => state.deliveries.filter((delivery) => delivery.orderId === orderId).flatMap((delivery) => delivery.lines.filter((line) => line.lineId === lineId).map((line) => ({ delivery, line })));
const deliveryLedger = (state, order, line) => {
  const entries = deliveryEntries(state, order.id, line.lineId);
  let gross = 0; let accepted = 0; let rejected = 0; let returned = 0;
  for (const { line: entry } of entries) {
    const quantity = positive(entry.quantity, 'delivery.quantity');
    gross += quantity;
    const initiallyAccepted = entry.accepted !== false;
    if (initiallyAccepted) accepted += quantity; else rejected += quantity;
    for (const resolution of Array.isArray(entry.resolutions) ? entry.resolutions : []) {
      const resolved = positive(resolution.quantity, 'resolution.quantity');
      if (resolved > quantity) throw new Error(`复验数量超过到货数量：${entry.lineId}`);
      if (resolution.disposition === 'accept') { if (initiallyAccepted) accepted += resolved; else { rejected -= resolved; accepted += resolved; } }
      if (resolution.disposition === 'return') { if (initiallyAccepted) accepted -= resolved; else rejected -= resolved; returned += resolved; }
    }
  }
  return { gross: round(gross), accepted: round(Math.max(0, accepted)), rejected: round(Math.max(0, rejected)), returned: round(returned), net: round(Math.max(0, accepted + rejected)) };
};
const syncOrderQuantities = (state, order) => { for (const line of order.lines) line.deliveredQuantity = deliveryLedger(state, order, line).net; return order; };
const uniformTotals = (lines, field) => { const units = new Set(lines.map((line) => line.unit)); return units.size === 1 ? round(lines.reduce((sum, line) => sum + line[field], 0)) : null; };

export class ProcurementStore extends ConstructionStore {
  async registerSupplier(args) { return this.withState(args, async (state, scope) => { const id = identifier(args.id || `supplier-${randomUUID()}`, 'id'); if (state.suppliers.some((supplier) => supplier.id === id)) throw new Error(`供应商已存在：${id}`); const supplier = { id, name: text(args.name, 'name'), contact: String(args.contact || '').slice(0, 200), leadTimeDays: args.leadTimeDays == null ? null : Math.max(0, Math.floor(finite(args.leadTimeDays, 'leadTimeDays'))), rating: args.rating == null ? null : Math.max(0, Math.min(5, finite(args.rating, 'rating'))), compliance: Array.isArray(args.compliance) ? args.compliance.slice(0, 50).map((item) => String(item).slice(0, 200)) : [], status: 'active', createdAt: new Date().toISOString() }; state.suppliers.push(supplier); return { action: 'register_supplier', ...scope, supplier }; }); }
  async approveChangeOrder(args) { return this.withState(args, async (state, scope) => { const changeOrder = state.changeOrders.find((item) => item.id === args.changeOrderId); if (!changeOrder) throw new Error('设计变更单不存在'); if (changeOrder.status !== 'proposed') throw new Error(`设计变更单当前状态不可审批：${changeOrder.status}`); const decision = args.decision === 'rejected' ? 'rejected' : args.decision === 'approved' ? 'approved' : null; if (!decision) throw new Error('decision 必须是 approved 或 rejected'); changeOrder.status = decision; changeOrder.reviewedBy = text(args.reviewedBy || scope.accountId, 'reviewedBy', 128); changeOrder.reviewedAt = new Date().toISOString(); changeOrder.reviewNote = String(args.note || '').slice(0, 1_000); return { action: 'approve_change_order', ...scope, changeOrder }; }); }
  async runConstructionWorkflow(args) {
    const workflowKey = typeof args.idempotencyKey === 'string' && args.idempotencyKey.trim() ? identifier(args.idempotencyKey.trim(), 'idempotencyKey') : null;
    if (workflowKey) {
      const current = await this.read(args);
      const cached = current.idempotency?.[`workflow:${workflowKey}`];
      if (cached && typeof cached === 'object') return { ...cached, replayed: true };
    }
    const snapshot = await this.read(args);
    try {
      const program = await this.createSpaceProgram(args);
      const plan = await this.generateFloorPlan({ ...args, spaces: program.spaces });
      const placedRooms = plan.rooms.filter((room) => room.status === 'placed');
      if (!placedRooms.length) throw new Error('平面方案没有可实体化的房间');
      if (plan.status === 'over_capacity' && args.allowPartial !== true) throw new Error('平面方案超出边界容量；设置 allowPartial=true 才能继续实体化已放置房间');
      const model = await this.materializeFloorPlanModel({ ...args, rooms: placedRooms, height: args.height ?? 3 });
      const quantities = await this.extractQuantities(args);
      const renovation = Array.isArray(args.renovationRooms) && args.renovationRooms.length
        ? await this.generateRenovationScope({ ...args, rooms: args.renovationRooms, id: args.renovationScopeId })
        : null;
      const bom = await this.generateBom({ ...args, quantities: renovation ? [...quantities.quantities, ...renovation.quantities] : quantities.quantities });
      const result = { action: 'run_construction_workflow', ...ensureProject(args), status: plan.status, program, plan, model, quantities, renovation, bom, steps: ['create_space_program', 'generate_floor_plan', 'materialize_floor_plan_model', 'extract_quantities', ...(renovation ? ['generate_renovation_scope'] : []), 'generate_bom_from_model'] };
      if (workflowKey) await this.withState(args, async (state) => { state.idempotency[`workflow:${workflowKey}`] = result; return result; });
      return result;
    } catch (error) {
      await this.restore(args, snapshot);
      throw error;
    }
  }
  async generateBom(args) { return this.withState(args, async (state, scope) => { const source = Array.isArray(args.quantities) ? args.quantities : state.quantities; if (!source.length) throw new Error('没有工程量；先执行 extract_quantities'); const bom = source.map((item, i) => { const materialCode = identifier(item.materialCode, `quantities[${i}].materialCode`); const quantity = positive(item.quantity, `quantities[${i}].quantity`); const unit = text(item.unit || 'ea', `quantities[${i}].unit`, 16); return { lineId: item.id || `${materialCode}-${i + 1}`, materialCode, description: text(item.description || materialCode, 'description'), quantity: round(quantity), unit, sourceElementId: item.elementId || null, sourceRevision: item.sourceRevision || null, status: 'draft' }; }); state.bom = bom; return { action: 'generate_bom_from_model', ...scope, bom, totals: bom.reduce((map, line) => { const key = `${line.materialCode}:${line.unit}`; map[key] = round((map[key] || 0) + line.quantity); return map; }, {}) }; }); }
  async compareQuotes(args) { return this.withState(args, async (state, scope) => { const quoteRows = rows(args.quotes, 'quotes'); const normalized = quoteRows.map((quote, i) => { const supplierId = identifier(quote.supplierId, `quotes[${i}].supplierId`); const items = rows(quote.items, `quotes[${i}].items`).map((item, j) => ({ lineId: identifier(item.lineId, `quotes[${i}].items[${j}].lineId`), unitPrice: money(item.unitPrice, `unitPrice`), quantity: positive(item.quantity, 'quantity'), currency: text(item.currency || 'CNY', 'currency', 3) })); const total = round(items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0), 2); return { id: quote.id || `quote-${randomUUID()}`, supplierId, validUntil: quote.validUntil || null, items, total, currency: items[0]?.currency || 'CNY', deliveryDays: quote.deliveryDays == null ? null : Math.max(0, Math.floor(finite(quote.deliveryDays, 'deliveryDays'))), terms: String(quote.terms || '').slice(0, 500) }; }); state.quotes = normalized; return { action: 'compare_supplier_quotes', ...scope, quotes: normalized.sort((a, b) => a.total - b.total), recommendation: normalized.length ? { lowestTotal: normalized[0].id, fastestDelivery: normalized.reduce((best, q) => q.deliveryDays != null && (best.deliveryDays == null || q.deliveryDays < best.deliveryDays) ? q : best, normalized[0]).id } : null, note: '推荐仅按总价与交期排序，不替代供应商资质、质量和合同审查。' }; }); }
  async calculateBudget(args) { return this.withState(args, async (state, scope) => { const items = Array.isArray(args.items) ? args.items : (state.quotes.flatMap((quote) => quote.items.map((item) => ({ ...item, supplierId: quote.supplierId, quoteId: quote.id })))); if (!items.length) throw new Error('没有可计价项'); const subtotal = round(items.reduce((sum, item) => sum + positive(item.quantity, 'quantity') * money(item.unitPrice, 'unitPrice'), 0), 2); const taxRate = Math.max(0, Math.min(1, finite(args.taxRate ?? 0, 'taxRate'))); const contingencyRate = Math.max(0, Math.min(1, finite(args.contingencyRate ?? 0, 'contingencyRate'))); const tax = round(subtotal * taxRate, 2); const contingency = round(subtotal * contingencyRate, 2); return { action: 'calculate_budget', ...scope, currency: args.currency || 'CNY', lines: items, subtotal, taxRate, tax, contingencyRate, contingency, total: round(subtotal + tax + contingency, 2), assumptions: ['税率和预备费由项目输入；未包含未提供的运输、安装、人工或付款条款。'] }; }); }
  async createPurchaseRequest(args) { return this.withState(args, async (state, scope) => { const bom = Array.isArray(args.lines) ? args.lines : state.bom; const lines = rows(bom, 'lines').map((line, i) => ({ lineId: identifier(line.lineId || line.materialCode, `lines[${i}].lineId`), materialCode: identifier(line.materialCode, 'materialCode'), quantity: positive(line.quantity, 'quantity'), unit: text(line.unit || 'ea', 'unit', 16), needBy: line.needBy || null })); const request = { id: args.id || `pr-${randomUUID()}`, title: text(args.title || '采购申请', 'title'), status: 'submitted', requester: text(args.requester || scope.accountId, 'requester', 128), lines, projectId: scope.projectId, taskId: scope.taskId, createdAt: new Date().toISOString(), note: String(args.note || '').slice(0, 1_000) }; state.purchaseRequests.push(request); return { action: 'create_purchase_request', ...scope, request }; }); }
  async createPurchaseOrder(args) { return this.withState(args, async (state, scope) => { const request = state.purchaseRequests.find((item) => item.id === args.requestId); const lines = Array.isArray(args.lines) ? args.lines : request?.lines; if (!lines?.length) throw new Error('采购订单需要 requestId 或 lines'); const orderId = identifier(args.id || `po-${randomUUID()}`, 'id'); if (state.purchaseOrders.some((item) => item.id === orderId)) throw new Error(`采购订单已存在：${orderId}`); const order = { id: orderId, requestId: request?.id || null, supplierId: identifier(args.supplierId, 'supplierId'), status: 'issued', currency: text(args.currency || 'CNY', 'currency', 3), lines: rows(lines, 'lines').map((line, i) => ({ lineId: identifier(line.lineId || `line-${i + 1}`, `lines[${i}].lineId`), materialCode: identifier(line.materialCode, 'materialCode'), quantity: positive(line.quantity, 'quantity'), unit: text(line.unit || 'ea', 'unit', 16), unitPrice: money(line.unitPrice, 'unitPrice'), deliveredQuantity: 0 })), createdAt: isoDate(args.createdAt, 'createdAt'), projectId: scope.projectId, taskId: scope.taskId }; uniqueIds(order.lines, 'lineId', '订单行'); order.subtotal = round(order.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0), 2); order.shipping = args.shipping == null ? 0 : round(Math.max(0, finite(args.shipping, 'shipping')), 2); order.total = round(order.subtotal + order.shipping, 2); state.purchaseOrders.push(order); return { action: 'create_purchase_order', ...scope, order }; }); }
  async recordDelivery(args) { return this.withState(args, async (state, scope) => { const order = state.purchaseOrders.find((item) => item.id === args.orderId); if (!order) throw new Error('采购订单不存在'); if (order.status === 'closed') throw new Error('采购订单已经关闭，不能继续收货'); const deliveryId = identifier(args.id || `delivery-${randomUUID()}`, 'id'); if (state.deliveries.some((item) => item.id === deliveryId)) throw new Error(`到货单已存在：${deliveryId}`); const inputLines = rows(args.lines, 'lines'); uniqueIds(inputLines, 'lineId', '到货行'); syncOrderQuantities(state, order); const deliveryLines = inputLines.map((line, i) => { const target = order.lines.find((item) => item.lineId === line.lineId); if (!target) throw new Error(`订单行不存在：${line.lineId}`); const quantity = positive(line.quantity, `lines[${i}].quantity`); const remaining = round(target.quantity - target.deliveredQuantity); if (quantity > remaining) throw new Error(`收货数量超过未收数量：${line.lineId}`); return { lineId: target.lineId, quantity, accepted: line.accepted !== false, lot: String(line.lot || '').slice(0, 100), note: String(line.note || '').slice(0, 500), resolutions: [] }; }); const delivery = { id: deliveryId, orderId: order.id, receivedAt: isoDate(args.receivedAt, 'receivedAt'), lines: deliveryLines, receiver: text(args.receiver || scope.accountId, 'receiver', 128), status: deliveryLines.every((line) => line.accepted) ? 'accepted' : 'inspection_required' }; state.deliveries.push(delivery); syncOrderQuantities(state, order); order.status = order.lines.every((line) => line.deliveredQuantity >= line.quantity) ? 'received' : 'partially_received'; return { action: 'record_delivery', ...scope, delivery, orderStatus: order.status }; }); }
  async reconcilePurchaseOrder(args) { return this.withState(args, async (state, scope) => { const order = state.purchaseOrders.find((item) => item.id === args.orderId); if (!order) throw new Error('采购订单不存在'); const lines = order.lines.map((line) => { const ledger = deliveryLedger(state, order, line); const remaining = round(Math.max(0, line.quantity - ledger.net)); return { lineId: line.lineId, materialCode: line.materialCode, ordered: line.quantity, delivered: ledger.net, receivedGross: ledger.gross, accepted: ledger.accepted, rejected: ledger.rejected, returned: ledger.returned, remaining, unit: line.unit, status: ledger.rejected > 0 ? 'inspection_required' : remaining > 0 ? 'partial' : 'complete' }; }); syncOrderQuantities(state, order); const status = lines.some((line) => line.rejected > 0) ? 'inspection_required' : lines.some((line) => line.remaining > 0) ? 'partially_received' : 'ready_to_close'; const reconciliation = { id: identifier(args.id || `reconciliation-${randomUUID()}`, 'id'), orderId: order.id, status, lines, totalOrdered: uniformTotals(lines, 'ordered'), totalDelivered: uniformTotals(lines, 'delivered'), totalAccepted: uniformTotals(lines, 'accepted'), totalRejected: uniformTotals(lines, 'rejected'), totalsByUnit: lines.reduce((map, line) => { map[line.unit] ||= { ordered: 0, delivered: 0, accepted: 0, rejected: 0, returned: 0, remaining: 0 }; for (const field of ['ordered', 'delivered', 'accepted', 'rejected', 'returned', 'remaining']) map[line.unit][field] = round(map[line.unit][field] + line[field]); return map; }, {}), generatedAt: new Date().toISOString() }; state.reconciliations.push(reconciliation); return { action: 'reconcile_purchase_order', ...scope, reconciliation, nextAction: status === 'ready_to_close' ? 'close_purchase_order' : status === 'inspection_required' ? 'resolve_delivery_discrepancy' : 'record_delivery' }; }); }
  async resolveDeliveryDiscrepancy(args) { return this.withState(args, async (state, scope) => { const order = state.purchaseOrders.find((item) => item.id === args.orderId); if (!order) throw new Error('采购订单不存在'); if (order.status === 'closed') throw new Error('采购订单已经关闭，不能处理差异'); const delivery = state.deliveries.find((item) => item.id === args.deliveryId && item.orderId === order.id); if (!delivery) throw new Error('到货单不存在'); const line = delivery.lines.find((item) => item.lineId === args.lineId); if (!line) throw new Error('到货行不存在'); const disposition = args.disposition === 'accept' || args.disposition === 'return' ? args.disposition : null; if (!disposition) throw new Error('disposition 必须是 accept 或 return'); if (disposition === 'accept' && line.accepted !== false) throw new Error('已验收物料不能重复复验接收'); const quantity = positive(args.quantity, 'quantity'); const resolutions = Array.isArray(line.resolutions) ? line.resolutions : []; const resolved = resolutions.reduce((sum, item) => sum + item.quantity, 0); if (quantity > round(line.quantity - resolved)) throw new Error('复验数量超过未处理差异'); const resolutionId = identifier(args.id || `resolution-${randomUUID()}`, 'id'); if (state.deliveries.some((item) => item.lines.some((entry) => entry.resolutions?.some((resolution) => resolution.id === resolutionId)))) throw new Error(`复验记录已存在：${resolutionId}`); const resolution = { id: resolutionId, disposition, quantity, resolvedBy: text(args.resolvedBy || scope.accountId, 'resolvedBy', 128), resolvedAt: isoDate(args.resolvedAt, 'resolvedAt'), note: String(args.note || '').slice(0, 500) }; line.resolutions = [...resolutions, resolution]; const target = order.lines.find((item) => item.lineId === line.lineId); const ledger = deliveryLedger(state, order, target); const deliveryHasOpenReject = delivery.lines.some((entry) => { const targetLine = order.lines.find((item) => item.lineId === entry.lineId); return deliveryLedger(state, order, targetLine).rejected > 0 && entry.accepted === false; }); delivery.status = deliveryHasOpenReject ? 'inspection_required' : 'resolved'; syncOrderQuantities(state, order); return { action: 'resolve_delivery_discrepancy', ...scope, resolution, delivery, lineLedger: ledger, nextAction: ledger.rejected > 0 ? 'resolve_delivery_discrepancy' : order.lines.some((item) => item.deliveredQuantity < item.quantity) ? 'record_delivery' : 'reconcile_purchase_order' }; }); }
  async closePurchaseOrder(args) { return this.withState(args, async (state, scope) => { const order = state.purchaseOrders.find((item) => item.id === args.orderId); if (!order) throw new Error('采购订单不存在'); if (order.status === 'closed') throw new Error('采购订单已经关闭'); syncOrderQuantities(state, order); if (order.lines.some((line) => Number(line.deliveredQuantity || 0) < Number(line.quantity || 0))) throw new Error('采购订单仍有未交数量，不能关闭'); if (order.lines.some((line) => deliveryLedger(state, order, line).rejected > 0)) throw new Error('采购订单存在未处理拒收物料，不能关闭'); order.status = 'closed'; order.closedBy = text(args.closedBy || scope.accountId, 'closedBy', 128); order.closedAt = new Date().toISOString(); order.closeNote = String(args.note || '').slice(0, 1_000); return { action: 'close_purchase_order', ...scope, order, nextAction: 'handover_to_accounts_payable' }; }); }
  async handoverToAccountsPayable(args) { return this.withState(args, async (state, scope) => { const order = state.purchaseOrders.find((item) => item.id === args.orderId); if (!order) throw new Error('采购订单不存在'); if (order.status !== 'closed') throw new Error('采购订单尚未关闭，不能交接应付'); if (state.paymentHandovers.some((item) => item.orderId === order.id && item.status !== 'cancelled')) throw new Error('该采购订单已经生成应付交接单'); const taxRate = args.taxRate == null ? 0 : Math.max(0, Math.min(1, finite(args.taxRate, 'taxRate'))); const tax = round(order.subtotal * taxRate, 2); const handover = { id: args.id || `payable-${randomUUID()}`, orderId: order.id, supplierId: order.supplierId, currency: order.currency, subtotal: order.subtotal, shipping: round(order.total - order.subtotal, 2), taxRate, tax, payable: round(order.total + tax, 2), invoiceNumber: String(args.invoiceNumber || '').slice(0, 100) || null, paymentTerms: String(args.paymentTerms || '').slice(0, 200), requestedBy: text(args.requestedBy || scope.accountId, 'requestedBy', 128), status: 'pending', createdAt: new Date().toISOString() }; state.paymentHandovers.push(handover); return { action: 'handover_to_accounts_payable', ...scope, handover, nextAction: 'review_payment_handover' }; }); }
  async reviewPaymentHandover(args) { return this.withState(args, async (state, scope) => { const handover = state.paymentHandovers.find((item) => item.id === args.handoverId); if (!handover) throw new Error('应付交接单不存在'); if (handover.status !== 'pending' && handover.status !== 'on_hold') throw new Error(`应付交接单当前状态不可审核：${handover.status}`); const decision = args.decision === 'approved' ? 'approved' : args.decision === 'rejected' ? 'rejected' : args.decision === 'on_hold' ? 'on_hold' : null; if (!decision) throw new Error('decision 必须是 approved、rejected 或 on_hold'); handover.status = decision; handover.reviewedBy = text(args.reviewedBy || scope.accountId, 'reviewedBy', 128); handover.reviewedAt = isoDate(args.reviewedAt, 'reviewedAt'); handover.reviewNote = String(args.note || '').slice(0, 1_000); handover.reviewHistory = [...(handover.reviewHistory || []), { decision, by: handover.reviewedBy, at: handover.reviewedAt, note: handover.reviewNote }]; return { action: 'review_payment_handover', ...scope, handover, nextAction: decision === 'approved' ? 'record_payment' : decision === 'rejected' ? 'revise_payment_handover' : 'review_payment_handover' }; }); }
  async revisePaymentHandover(args) { return this.withState(args, async (state, scope) => { const handover = state.paymentHandovers.find((item) => item.id === args.handoverId); if (!handover) throw new Error('应付交接单不存在'); if (handover.status !== 'rejected' && handover.status !== 'on_hold') throw new Error('只有驳回或挂起的应付交接单可以修改'); if (handover.paid > 0) throw new Error('已有付款的应付交接单不能修改'); const next = {}; if (args.invoiceNumber !== undefined) next.invoiceNumber = String(args.invoiceNumber || '').slice(0, 100) || null; if (args.paymentTerms !== undefined) next.paymentTerms = String(args.paymentTerms || '').slice(0, 200); if (args.taxRate !== undefined) { const taxRate = Math.max(0, Math.min(1, finite(args.taxRate, 'taxRate'))); next.taxRate = taxRate; next.tax = round(handover.subtotal * taxRate, 2); next.payable = round(handover.subtotal + handover.shipping + next.tax, 2); next.balance = next.payable; } if (!Object.keys(next).length) throw new Error('至少提供 invoiceNumber、paymentTerms 或 taxRate'); Object.assign(handover, next); handover.revision = (handover.revision || 0) + 1; handover.status = 'pending'; handover.revisedBy = text(args.revisedBy || scope.accountId, 'revisedBy', 128); handover.revisedAt = isoDate(args.revisedAt, 'revisedAt'); handover.revisionNote = String(args.note || '').slice(0, 1_000); return { action: 'revise_payment_handover', ...scope, handover, nextAction: 'review_payment_handover' }; }); }
  async recordPayment(args) { return this.withState(args, async (state, scope) => { const handover = state.paymentHandovers.find((item) => item.id === args.handoverId); if (!handover) throw new Error('应付交接单不存在'); if (handover.status !== 'approved' && handover.status !== 'partially_paid') throw new Error('应付交接单尚未审核通过'); const paymentId = identifier(args.id || `payment-${randomUUID()}`, 'id'); if (state.payments.some((item) => item.id === paymentId)) throw new Error(`付款记录已存在：${paymentId}`); const alreadyPaid = round(state.payments.filter((item) => item.handoverId === handover.id).reduce((sum, item) => sum + item.amount, 0), 2); const amount = args.amount == null ? round(handover.payable - alreadyPaid, 2) : money(args.amount, 'amount'); if (amount <= 0) throw new Error('付款金额必须大于 0'); if (amount > round(handover.payable - alreadyPaid, 2)) throw new Error('付款金额超过未付余额'); const payment = { id: paymentId, handoverId: handover.id, orderId: handover.orderId, amount, currency: handover.currency, paidBy: text(args.paidBy || scope.accountId, 'paidBy', 128), paidAt: isoDate(args.paidAt, 'paidAt'), reference: String(args.reference || '').slice(0, 120) || null, note: String(args.note || '').slice(0, 500) }; state.payments.push(payment); const paid = round(alreadyPaid + amount, 2); handover.paid = paid; handover.balance = round(handover.payable - paid, 2); handover.status = handover.balance === 0 ? 'paid' : 'partially_paid'; return { action: 'record_payment', ...scope, payment, handover, nextAction: handover.status === 'paid' ? 'close_finance' : 'record_payment' }; }); }
  async closeFinance(args) { return this.withState(args, async (state, scope) => { const handover = state.paymentHandovers.find((item) => item.id === args.handoverId); if (!handover) throw new Error('应付交接单不存在'); if (handover.status === 'closed') throw new Error('财务交接已经关闭'); if (handover.status !== 'paid') throw new Error('应付交接单尚未全部付款，不能关闭财务交接'); handover.status = 'closed'; handover.closedBy = text(args.closedBy || scope.accountId, 'closedBy', 128); handover.closedAt = isoDate(args.closedAt, 'closedAt'); handover.closeNote = String(args.note || '').slice(0, 1_000); return { action: 'close_finance', ...scope, handover, workflowStatus: 'complete', nextAction: null }; }); }
  async createChangeOrder(args) { return this.withState(args, async (state, scope) => { const changes = rows(args.changes, 'changes').map((change, i) => ({ id: change.id || `change-${i + 1}`, targetId: identifier(change.targetId, 'targetId'), field: text(change.field, 'field', 100), before: change.before ?? null, after: change.after ?? null, reason: text(change.reason || '未填写变更原因', 'reason', 500) })); const changeOrder = { id: args.id || `co-${randomUUID()}`, title: text(args.title || '设计变更', 'title'), status: 'proposed', requestedBy: text(args.requestedBy || scope.accountId, 'requestedBy', 128), changes, impact: { cost: args.impact?.cost == null ? null : finite(args.impact.cost, 'impact.cost'), days: args.impact?.days == null ? null : finite(args.impact.days, 'impact.days') }, createdAt: new Date().toISOString(), projectId: scope.projectId, taskId: scope.taskId }; state.changeOrders.push(changeOrder); return { action: 'create_change_order', ...scope, changeOrder }; }); }
}
