/*
 * Generated from Tencent Cloud MPS system voice page:
 * https://cloud.tencent.com/document/product/862/129151
 * Updated by script on 2026-03-24T15:11:41.972Z
 */

export type TencentSystemVoice = {
  index: number;
  voiceId: string;
  langCode: string;
  langZh: string;
  gender: 'male' | 'female';
  genderZh: string;
  ageZh: string;
  nameZh: string;
  sampleLabel: string;
};

export const TENCENT_SYSTEM_VOICES: TencentSystemVoice[] = [
  {
    "index": 1,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "中文",
    "nameZh": "沉稳高管",
    "sampleLabel": "0001_男性_中年_中文.mp3",
    "voiceId": "s1_8ChrieRlcxoc8QaSlkXujr5SPRhKXdFb66GHhlSzFqHt9BlxftgEC2ZKIQ1q2cGJyYIh4ySlO8UymaGg4Q==",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 2,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "中文",
    "nameZh": "播音主播",
    "sampleLabel": "0002_女性_中年_中文.mp3",
    "voiceId": "s1_B5m66v1MZpN2rO2G960udMEopMYMRdYs6WSkNLJ+qmAnCRusANJ9d016oCFi624kJGJO50xh",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 3,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "妩媚御姐",
    "sampleLabel": "0003_女性_青年_中文.mp3",
    "voiceId": "s1_9JReMurR45vnaKbRgpaL1QrAL2jDFatNfCqoawC8HMxdwLkGAku1Ean17wwM1DlvuzNAbyXa8g==",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 4,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "潇洒不羁",
    "sampleLabel": "0004_男性_青年_中文.mp3",
    "voiceId": "s1_0lAc7P6d8iy/HGSGnnMGX5FLb8pJwFqkqtNKfhOLMGVSpPwEWzx+BMscVwInPK660Qolkzxp7xTmGAyGclUFUeY=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 5,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "嚣张御姐",
    "sampleLabel": "0005_女性_青年_中文.mp3",
    "voiceId": "s1_d/yKj25zPnuUURVi64E6M78KH/sQ6TXrG8PeYR2/0/bqW0P/Ug==",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 6,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "机器人腔",
    "sampleLabel": "0006_男性_青年_中文.mp3",
    "voiceId": "s1_ztAZoOVtdtfWNjK/yHUUsbZf/1PUSlZxcBZ3reJv1+6FtgY=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 7,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "中文",
    "nameZh": "温和大婶",
    "sampleLabel": "0007_女性_中年_中文.mp3",
    "voiceId": "s1_96+Ls0P/X/+KnzaTrvYzrwgmMe9N2xMq1Uvt3CUxuwKWa9290fwjIP9A/n25UwZChmchiVwd/vERrOMRNQ==",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 8,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "中文",
    "nameZh": "港普空乘",
    "sampleLabel": "0008_女性_中年_中文.mp3",
    "voiceId": "s1_ccGBil9z7gkJyqdVh30iywHNyqeWAHS1DvpN/f4mfJ3Sjwv4m6ADuRJyN1XeaK62nK7WnCBA2ZvQ8Qx9oX4=",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 9,
    "genderZh": "男性",
    "ageZh": "老年",
    "langZh": "中文",
    "nameZh": "幽默老大爷",
    "sampleLabel": "0009_男性_老年_中文.mp3",
    "voiceId": "s1_BJkWIK4/owwQBOPk7RYWVablZyim3Ia7nGauRV9qWrsNu+1ehirK4O9DxL3BMOjrV80CjvHmoaYi",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 10,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "温润磁声",
    "sampleLabel": "0010_男性_青年_中文.mp3",
    "voiceId": "s1_OlOZXi7ueR5i6bVzMJTuBnTG/Y6O0CmH8M1k9Y9xAGrpC95AZeDdqTbybETno3MtftESCQ==",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 11,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "清脆闺蜜",
    "sampleLabel": "0011_女性_青年_中文.mp3",
    "voiceId": "s1_FGDHA2NnzICeAgkAu/O6SOLhC5tVtW7eWIhZaeY7G9Q3e/vHtNCQWxyZ0qYtYXiIPlEdkbXr",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 12,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "中文",
    "nameZh": "磁性播报员",
    "sampleLabel": "0012_男性_中年_中文.mp3",
    "voiceId": "s1_K7CtFYOSdu6lMxWca8AV0vcKZAs+Q75LuzGSiVZJEnwRAb5XFAbucv9mAYJFDHGyvVTlnqmlAYBQ",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 13,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "温柔甜美",
    "sampleLabel": "0013_女性_青年_中文.mp3",
    "voiceId": "s1_Ovbon7dbN63cNliuGJeb8a6+7SMpfAE2zafK2TiWYCuoBJX3RQxi8VZvTBwCfd44GTEZoKg=",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 14,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "南腔质朴",
    "sampleLabel": "0014_男性_青年_中文.mp3",
    "voiceId": "s1_A6YwOmB9AU4gcKxDzU11Z53TWB91hhUmyMh9KmyyxjrRUhqLnhb0V9Qu/GnsFlWmImZxNpRHeldyCYRewA==",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 15,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "中文",
    "nameZh": "抒情姐姐",
    "sampleLabel": "0015_女性_中年_中文.mp3",
    "voiceId": "s1_SgodNIsvxgD3r8eEuzYmB8Y/yP4W3rwGMdm74hcNsUy5qxowS2XvKrpGVHzLafsSpc4aj6M=",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 16,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "温柔阳光",
    "sampleLabel": "0016_男性_青年_中文.mp3",
    "voiceId": "s1_08XsH0ch01S98Gsr+cMI8pgu9NbxyLvba1PIC2eL7+OAWlKRz+MiIb3bO4TTnaKvp7tmqe0RBQ==",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 17,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "中文",
    "nameZh": "温柔少女声",
    "sampleLabel": "0017_女性_少年_中文.mp3",
    "voiceId": "s1_FdaOYPrTugqzcDM0oTF5w9nWN+lgMy9OY64fFR82/vGS6w+42WXMwnrLOfZm3fY4C7SSZA==",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 18,
    "genderZh": "女性",
    "ageZh": "老年",
    "langZh": "中文",
    "nameZh": "慈祥奶奶",
    "sampleLabel": "0018_女性_老年_中文.mp3",
    "voiceId": "s1_osdD+ReZV2enyJGNtniAUHz0k4QYTiQz6ea012IblB3hZ3h8U2AaOMrUmMLHWuX9c3ybG8oxbsT4KHThFA==",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 19,
    "genderZh": "男性",
    "ageZh": "少年",
    "langZh": "中文",
    "nameZh": "呆萌少年",
    "sampleLabel": "0019_男性_少年_中文.mp3",
    "voiceId": "s1_vcIfg4EcxhmPtPtHbXuMzwHbgiVGXvsOLx6S+2lgg7QbHBHoxHsP87vuXlw/ZjlaAzUWdLDY",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 20,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "诗意电台",
    "sampleLabel": "0020_男性_青年_中文.mp3",
    "voiceId": "s1_CIPvuaQVRFXv9NT4Cgij5BhGKoxpYQDPtzOfN5sxuEQrN1O2ZY6vEGX8eKkDDf71FeRnfnw=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 21,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "磁性抒情",
    "sampleLabel": "0021_男性_青年_中文.mp3",
    "voiceId": "s1_iWay8xZE9nWeUwd66czvRDO/cvcyLQsU0gdJpUs0t0xPiyQbgFwjrJMYV18uGUZYiwFRrA6/prU=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 22,
    "genderZh": "男性",
    "ageZh": "少年",
    "langZh": "中文",
    "nameZh": "率真弟弟",
    "sampleLabel": "0022_男性_少年_中文.mp3",
    "voiceId": "s1_AlETc+zdrCQvA9Dq2a7hepRTigyIvZYmv87w+pmq/p7ipZsCssa8H1iulcaW3uqp8QEVdiTp3EUbqisLQeI=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 23,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "真诚鼓励",
    "sampleLabel": "0023_男性_青年_中文.mp3",
    "voiceId": "s1_yCXmpTp2XXTfPWP9s26x3c20E2q7Qq3exBMaCZNP/JDQIf4Dv3pzg8hzg6IBLcPKilP/d/2fWZ8=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 24,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "温柔学姐",
    "sampleLabel": "0024_女性_青年_中文.mp3",
    "voiceId": "s1_SfzDCdXfjl8umGvGbW0odu58xkPD2f5DEJemRnkPG4nti/LdXa46/rz1E7s27vixGhcsNVYmxmc=",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 25,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "中文",
    "nameZh": "清脆少女",
    "sampleLabel": "0025_女性_少年_中文.mp3",
    "voiceId": "s1_YU0+CIFwOnMlVQ6SMOOSt7GgHypSxJBWZaO6sXoyINiD55O84YZp5KHQU4ShbCDvZMo5xHU=",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 26,
    "genderZh": "男性",
    "ageZh": "少年",
    "langZh": "中文",
    "nameZh": "清澈邻家弟弟",
    "sampleLabel": "0026_男性_少年_中文.mp3",
    "voiceId": "s1_EHeYfDi5zS01aBNPX2GDb3aLlKIBAhZk5ajHblCQiZSgjPH0dvpo8EUtRpbBxfVQdW5r2pTUczRFDrk=",
    "langCode": "zh",
    "gender": "male"
  },
  {
    "index": 27,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "中文",
    "nameZh": "南腔柔软",
    "sampleLabel": "0027_女性_青年_中文.mp3",
    "voiceId": "s1_BwkqO2512s6ntSG5aqtB8ygDeyzF5RfISz1scZvaX96StEh+DCSkNQuthsFyLW2+ATVNfA==",
    "langCode": "zh",
    "gender": "female"
  },
  {
    "index": 28,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "粤语",
    "nameZh": "粤语主持女",
    "sampleLabel": "0028_女性_青年_粤语.mp3",
    "voiceId": "s1_gyKUD79yEParTSQ0xLVTJJpRh6lckIEyKa3SALQwAqikjEh2cy4BTmEDTiZhiMxxrxRPUDPHwg==",
    "langCode": "yue",
    "gender": "female"
  },
  {
    "index": 29,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "粤语",
    "nameZh": "粤语温柔女",
    "sampleLabel": "0029_女性_青年_粤语.mp3",
    "voiceId": "s1_3/3yURLd/VjaM7fKsrehcAxh92wzXTC4HMVsCsFxfOKp3bEu4+DtQDXzuLQ=",
    "langCode": "yue",
    "gender": "female"
  },
  {
    "index": 30,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "粤语",
    "nameZh": "粤语主持男",
    "sampleLabel": "0030_男性_青年_粤语.mp3",
    "voiceId": "s1_av4KKOVrB8QkdiYthtuWlBI9+UTOvnIpQqnB71WGbOJwf2gWwzrNIVtCnZ14l1QE88SOkgA9lQ==",
    "langCode": "yue",
    "gender": "male"
  },
  {
    "index": 31,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "粤语",
    "nameZh": "粤语深情男",
    "sampleLabel": "0031_男性_青年_粤语.mp3",
    "voiceId": "s1_wZVcI3WtJbUOgH2eDwPF/pU92jHObEPk1KOd7/Mk6yuSO/JRa90Kn9ZIjtY=",
    "langCode": "yue",
    "gender": "male"
  },
  {
    "index": 32,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "粤语",
    "nameZh": "粤语甜美女",
    "sampleLabel": "0032_女性_青年_粤语.mp3",
    "voiceId": "s1_fIlnOOwiI0iN1Qnj0tqPRCVGCsGqoOTyrsrqXu2sseACVT06HWB6uZfP",
    "langCode": "yue",
    "gender": "female"
  },
  {
    "index": 33,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "粤语",
    "nameZh": "粤语亲切女",
    "sampleLabel": "0033_女性_青年_粤语.mp3",
    "voiceId": "s1_AUjLao/rTPVUN/sGPKhQi4fEYFOWslDzzSCqUu2DkFLnSH+kcCzezzCtBw==",
    "langCode": "yue",
    "gender": "female"
  },
  {
    "index": 34,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "英语",
    "nameZh": "英美磁性男",
    "sampleLabel": "0034_男性_青年_英语.mp3",
    "voiceId": "s1_Df/v5n1WwYCiC792LluRFyzBGoePGHkffFIOJrVvaoCIhl0x7k7jv2imsnmmyfs=",
    "langCode": "en",
    "gender": "male"
  },
  {
    "index": 35,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "英语",
    "nameZh": "英伦优雅女",
    "sampleLabel": "0035_女性_中年_英语.mp3",
    "voiceId": "s1_G4UW2NgP5sdyrKOmsvoD45+xj0Dr+yZlsZh1AaE7/WT1h3JMfNQA79Hom3HR",
    "langCode": "en",
    "gender": "female"
  },
  {
    "index": 36,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "英语",
    "nameZh": "澳洲阳光男",
    "sampleLabel": "0036_男性_青年_英语.mp3",
    "voiceId": "s1_1pWaaWGUTzYMvlIWj4St69bzLMwzU3VCYZc1hUct69sAoT6QFYeZTfoJRZM=",
    "langCode": "en",
    "gender": "male"
  },
  {
    "index": 37,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "英语",
    "nameZh": "美式耳语女",
    "sampleLabel": "0037_女性_青年_英语.mp3",
    "voiceId": "s1_aJxc84R2PxxKlVy2Ehw29TK4eIYzlacW/YZD+p+fumsIHJ1j1JkOkdlKdKSJYLg=",
    "langCode": "en",
    "gender": "female"
  },
  {
    "index": 38,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "英语",
    "nameZh": "印度勤奋男",
    "sampleLabel": "0038_男性_青年_英语.mp3",
    "voiceId": "s1_GEK3WJ3G8TG6+eT31IF80x1opLHZjjWoRg2hG3r2B3uafPz/z1Wn2ch38Ig=",
    "langCode": "en",
    "gender": "male"
  },
  {
    "index": 39,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "英语",
    "nameZh": "美式温柔男",
    "sampleLabel": "0039_男性_青年_英语.mp3",
    "voiceId": "s1_7+oOItdP5O2Z2R0P8k1P76tkcg/Rq8YbE/0L3qndAhL5N3uLJHPLpdKhiRXAjluncw==",
    "langCode": "en",
    "gender": "male"
  },
  {
    "index": 40,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语知性男",
    "sampleLabel": "0040_男性_青年_日语.mp3",
    "voiceId": "s1_ZknEeTVbICGHHnFnffhyY5/yWi7hyknekcQ1lc+AAQ+0D85cBIXLWCvE7TV3WlNKizzo",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 41,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语果断公主",
    "sampleLabel": "0041_女性_青年_日语.mp3",
    "voiceId": "s1_00ZW7lV52dytIF4m/Bj9eUp2eRAcpiygkJ9oFIxwlpo16MQN1IQJThitQ5RHffEpZA==",
    "langCode": "ja",
    "gender": "female"
  },
  {
    "index": 42,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语骑士",
    "sampleLabel": "0042_男性_青年_日语.mp3",
    "voiceId": "s1_oNzQgAtFsrqp7DhNpqV9kJJccskR3F48K3ewV5/11BS8Np0lsZ/ZsFXtkc4=",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 43,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "日语",
    "nameZh": "日语强势男",
    "sampleLabel": "0043_男性_中年_日语.mp3",
    "voiceId": "s1_jKhpBYvk9J8kDb7sESoJfr1j8yme1gLDhApwRrJte3PUO9X6Nvy1LxFXxZ4=",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 44,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语指挥官",
    "sampleLabel": "0044_男性_青年_日语.mp3",
    "voiceId": "s1_BHy2TiUBUqdSA4d3u2rnBRzfcY/kuA1vRZEe3czd3HtHQQ9oJEgDKZTQQHWfDUo/FA==",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 45,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语冷漠女王",
    "sampleLabel": "0045_女性_青年_日语.mp3",
    "voiceId": "s1_COyz6p7sNHn7mKCb/WJwXvbRheRuBklU6he7lghUias8woT1sG7/qmRk",
    "langCode": "ja",
    "gender": "female"
  },
  {
    "index": 46,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语稳重女",
    "sampleLabel": "0046_女性_青年_日语.mp3",
    "voiceId": "s1_vJ5cU4kVIPnkCQRX0ow0Slk7RdRkOTNH5JiZMqVxBmZVcjNMY4+NVQM74ZlmmFRW",
    "langCode": "ja",
    "gender": "female"
  },
  {
    "index": 47,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语温柔管家",
    "sampleLabel": "0047_男性_青年_日语.mp3",
    "voiceId": "s1_3gMxcDIMLuJmxQRlusjjjB/IrO1yHiHf70T0ZjAprnNpEVtIfhYxoig5FAn5",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 48,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语善良女",
    "sampleLabel": "0048_女性_青年_日语.mp3",
    "voiceId": "s1_nPZrDXvn7OoSIyky3qq/+TnZ8tWEgspCbDpiIJf2ZUjNyImBECeS3yA=",
    "langCode": "ja",
    "gender": "female"
  },
  {
    "index": 49,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语沉静女",
    "sampleLabel": "0049_女性_青年_日语.mp3",
    "voiceId": "s1_KU/dDTVNDW0DrJeFk57SUseZwrRo37Hl8hAs2VfnlFHht0pNGvpoa1M=",
    "langCode": "ja",
    "gender": "female"
  },
  {
    "index": 50,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语开朗男",
    "sampleLabel": "0050_男性_青年_日语.mp3",
    "voiceId": "s1_icZG5n4h1gxSMs+D6uUoI92JYIW+fb51UI9/9YIrHLsXefvE7dev70UysQx4sXkY",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 51,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "日语",
    "nameZh": "日语居酒屋老板",
    "sampleLabel": "0051_男性_中年_日语.mp3",
    "voiceId": "s1_kI0DL4W0dzacN1NAEQYWhfyC2YqZdAjgeOmxa3rxr3PFyqJsnaMgR2KFMAyLv6vljLAC4V4=",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 52,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语运动男生",
    "sampleLabel": "0052_男性_青年_日语.mp3",
    "voiceId": "s1_4ivXCDCv3Bv0Vg2jw7UDrZL9ieGSfDB9En1pwCqER20kTkF04PIPC3xjaWQDWw==",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 53,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语天真男",
    "sampleLabel": "0053_男性_青年_日语.mp3",
    "voiceId": "s1_zwXJU3TU1594g/n+duvP9PIQ9Pw84ep4YAEgVTBBqMu4qsh3ycKjuwBdJks=",
    "langCode": "ja",
    "gender": "male"
  },
  {
    "index": 54,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "日语",
    "nameZh": "日语甜美少女",
    "sampleLabel": "0054_女性_青年_日语.mp3",
    "voiceId": "s1_pn+8r5z+jcwLNV/uT/7x2xTRL8XOIwaDwrASNnGrvpAZ1QSMK7M3c+U5n0lKMPk=",
    "langCode": "ja",
    "gender": "female"
  },
  {
    "index": 55,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "荷兰语",
    "nameZh": "荷兰语少女",
    "sampleLabel": "0055_女性_少年_荷兰语.mp3",
    "voiceId": "s1_psqOUjJ4DPESBWcbmierPd8Wmn/RB5ddOo4LjHR58QxfIGMcyfMQnNgFNK7K3Q==",
    "langCode": "nl",
    "gender": "female"
  },
  {
    "index": 56,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "荷兰语",
    "nameZh": "荷兰语霸道男",
    "sampleLabel": "0056_男性_青年_荷兰语.mp3",
    "voiceId": "s1_MvkmzBz2vA29AHqM0sCHoyWNGhJybxHLwE9EAytKkpr7d568fWXJn+QW",
    "langCode": "nl",
    "gender": "male"
  },
  {
    "index": 57,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "越南语",
    "nameZh": "越南语少女",
    "sampleLabel": "0057_女性_少年_越南语.mp3",
    "voiceId": "s1_lCW+Vg8bgToYE7XXjDA7/YH2nh42MxwcEjP6KwQeoERMB6jK/xaU9LdLLK+jVFSTqbZt",
    "langCode": "vi",
    "gender": "female"
  },
  {
    "index": 58,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语甜美姐姐",
    "sampleLabel": "0058_女性_中年_韩语.mp3",
    "voiceId": "s1_i3TYX9r/YyNFfmLIS9z+gKiKozwmQ8o5VHdu2CFHrsPrKjTyEZfPpQ==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 59,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语犀利男友",
    "sampleLabel": "0059_男性_中年_韩语.mp3",
    "voiceId": "s1_2lX5SsYgg4xki9rf70ei0rKPAR0wVM75QU15/0sZKpEXp0Af1/pPSPmQdfG7rFJF",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 60,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语迷人姐姐",
    "sampleLabel": "0060_女性_青年_韩语.mp3",
    "voiceId": "s1_Yg+kpo9A3t0rtcJsLyu4tP0OPdysti+FBbteBlvUYKQk4uZqe4fw73gusmfCdY0=",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 61,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语腼腆女",
    "sampleLabel": "0061_女性_青年_韩语.mp3",
    "voiceId": "s1_+WnjeOU4zN5h07Mbpn1Ct091SlqyFyNmmv/o4OfyCOzABcAVPZ8=",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 62,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语权威姐姐",
    "sampleLabel": "0062_女性_中年_韩语.mp3",
    "voiceId": "s1_iZpdWUUR0hcn1IjuOKS8xuiiDMfhuNlx2Bfvb993/jBr0InRkgRcBwjTLek2",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 63,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语严厉老板",
    "sampleLabel": "0063_男性_中年_韩语.mp3",
    "voiceId": "s1_+qpj0LBYMsDdhdc3P008JmFgcA1u89mV7Vn/p5Ja3bGZ8W+gO1eiAts=",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 64,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语温柔女",
    "sampleLabel": "0064_女性_青年_韩语.mp3",
    "voiceId": "s1_LdMbmwKrwmdJEX5SsHcLQoa3ijO6zK0v2EEOgEBHEqq/DhB9SJ48hg==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 65,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语花花公子",
    "sampleLabel": "0065_男性_青年_韩语.mp3",
    "voiceId": "s1_Fyq1f3uj1XoGNJjbHzyd+z56iIlRHjkKYM/xcoWrjCe9qdtnX30C1DRkQhOA",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 66,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语优雅公主",
    "sampleLabel": "0066_女性_青年_韩语.mp3",
    "voiceId": "s1_WMoRng3iYER+CWXMesOfjkUvcMRMRdSTUA7zCLV1hj5TBQ2++zA5MhIKwUm7Dw==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 67,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语女战士",
    "sampleLabel": "0067_女性_青年_韩语.mp3",
    "voiceId": "s1_s611cpYTycO/9r6P1N6z62qlJeF2Jaxr/lsYD49w6SqkwjMq7N/BmQuhyO+eSjxhWA==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 68,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语强有力男",
    "sampleLabel": "0068_男性_青年_韩语.mp3",
    "voiceId": "s1_TDZKnbmnMwrbdH0wKFeRca8ShfzEdup4aR7sk4Z8n2bs5nunDoQxRSE=",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 69,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语沉静女",
    "sampleLabel": "0069_女性_青年_韩语.mp3",
    "voiceId": "s1_fwbiltjbOe+tXCp+twOEPcceAfn0t3MvdeAYd6usCVjazSjxb9+A",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 70,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语热情男",
    "sampleLabel": "0070_男性_青年_韩语.mp3",
    "voiceId": "s1_ZWGqxQXGQFK+VZvM6S+MAbH8PyyaLaXKxwslEaibhUknACsdc2EOdJoZV8Y3RXU=",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 71,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语舒缓女",
    "sampleLabel": "0071_女性_中年_韩语.mp3",
    "voiceId": "s1_yCho6nNUgpu0wz2xx2U/gubH9JD3Uodf9sCtN1xkvK0zczylL1CazQkJoQ==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 72,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语知性学长",
    "sampleLabel": "0072_男性_青年_韩语.mp3",
    "voiceId": "s1_rxgPOnuotueG2m5rOBJSh7t4s9M2Jy4uoO2psaQ1X+Phf85NAsVcN27R5Q52RSugWQ==",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 73,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语优雅女士",
    "sampleLabel": "0073_女性_中年_韩语.mp3",
    "voiceId": "s1_Zt8d3NZ6QKmH13AJG24MN47n8PcIeJl3wRgqk2T2pl0vtQ9APvOpWVw=",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 74,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语纯真男孩",
    "sampleLabel": "0074_男性_青年_韩语.mp3",
    "voiceId": "s1_r8Ix/JxGstBYLWDledxk3lLcDDQMyULNMwAvj/5qnz/yfKbsLhHI/39U",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 75,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语魅惑姐姐",
    "sampleLabel": "0075_女性_中年_韩语.mp3",
    "voiceId": "s1_X+HuVGT27uWSp8VWK1AMTXo1bQapIYxf5c+55iDJ4KDgZZn+B0+lr47Snunr",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 76,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语勇敢女",
    "sampleLabel": "0076_女性_青年_韩语.mp3",
    "voiceId": "s1_H4DmRtJJzmUP7FmiS4FSzsjkLWYV6Gu9UIe0lnLiCzGUQWCG0t81PJDZtLdkZA==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 77,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语绅士男",
    "sampleLabel": "0077_男性_中年_韩语.mp3",
    "voiceId": "s1_prGO9qNtfHYZV+ytMcTte8Y0B1QOBpKS7CWk4Ep924iVrZQkFDp6a7kiZSw=",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 78,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语甜美女王",
    "sampleLabel": "0078_女性_青年_韩语.mp3",
    "voiceId": "s1_bybeUBrgSEWgYi/CaJRskrRyLFDOjcQbwnezwdkZjdjtIqseV51g1hy+6eM=",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 79,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语冷静男",
    "sampleLabel": "0079_男性_青年_韩语.mp3",
    "voiceId": "s1_9zGXht9PxOZX+GpoFlYCK2TDc59tsfCdZ8NgBqwaHOJiTHkbJEnQHHecNw==",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 80,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语神秘女",
    "sampleLabel": "0080_女性_青年_韩语.mp3",
    "voiceId": "s1_LWo5l+a5IbmZoRoLeez0fpW00YbIF77bMsqHGCjXPgGPbFIlIYypkNr5N9jW",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 81,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语古怪女",
    "sampleLabel": "0081_女性_青年_韩语.mp3",
    "voiceId": "s1_2FGrSPKwNqYNampc7IjB/BhCNqU8agVHlJD468UQKB09FHz08qguklA=",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 82,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语强势男",
    "sampleLabel": "0082_男性_青年_韩语.mp3",
    "voiceId": "s1_7prCgJjoYQi0owY4eIVwc6P7pJ40WJPetYxXqqvR/HKB0rVbXbX3ZAgV",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 83,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语可靠男",
    "sampleLabel": "0083_男性_青年_韩语.mp3",
    "voiceId": "s1_Pk6XnBUZwVJs1zOYN+Imq0Vtpk3ey5b+JuGhHp3GsIBGMHesr8OrHseHWgU=",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 84,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语大姐姐",
    "sampleLabel": "0084_女性_中年_韩语.mp3",
    "voiceId": "s1_Ue9mHCsmLFwYhkmdtiSuqJA2tMt84e4Qw02sn+2/aiQQJ1aJ4/hckGJGP0MiSoSy",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 85,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语冷漠女",
    "sampleLabel": "0085_女性_青年_韩语.mp3",
    "voiceId": "s1_4h4YmFAPJxf1FntX5BHUoPb1ajdf1KkhPVJf0Ut6imCiVirqyP3T",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 86,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语高傲女",
    "sampleLabel": "0086_女性_青年_韩语.mp3",
    "voiceId": "s1_zu6iRa/bux7UWsCiIgWv1gvynPFJUuGEcIQEIQCtDWVxLxTDmIw6ljl8",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 87,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语调皮姐",
    "sampleLabel": "0087_女性_中年_韩语.mp3",
    "voiceId": "s1_3nh5IqBW0QOCr987DPXsNXxIN3Qbuuy5U83ZGpmRm4H/RYiC8iv3ZQuaUjQZIJxJ3jA=",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 88,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语好斗男",
    "sampleLabel": "0088_男性_中年_韩语.mp3",
    "voiceId": "s1_mT1Vc6h9BArWmGdjOmj0oGspPZMTkdVKjZ9XvgDMD052bvXeTs3eOAA1sXWAsg==",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 89,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语灵动女",
    "sampleLabel": "0089_女性_青年_韩语.mp3",
    "voiceId": "s1_CgZX1rjVfXcTMM/BvTjrtEYEMe+DpFWlT8Iyz85wTwGf0UzJFgJzlWJB",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 90,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语男教师",
    "sampleLabel": "0090_男性_中年_韩语.mp3",
    "voiceId": "s1_bs6a6u6nszfvtWKmC3MHNDbTsiwMwv2ofUEPQJjaIC9pQIji3Y9c7f1f",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 91,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "韩语",
    "nameZh": "韩语运动少女",
    "sampleLabel": "0091_女性_少年_韩语.mp3",
    "voiceId": "s1_OUNIFJ9uhQwrGN/o71ngY2fU94fVbOYMxoRt7xJqNpxWvC3ZP8jQeZPsrw==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 92,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "韩语",
    "nameZh": "韩语占有欲男",
    "sampleLabel": "0092_男性_中年_韩语.mp3",
    "voiceId": "s1_jUkXiMuMV7pJmvszcJXYIjvjK536NHXcfsw6qnusZll5+FIXYcvj+Z33lKw=",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 93,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语坚毅女",
    "sampleLabel": "0093_女性_青年_韩语.mp3",
    "voiceId": "s1_HQC6+mFpSZB4Nndu8Ys9d7y509axd8cXkpZuAkyBQjEk+pt5BlCc2DsP",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 94,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语自大男",
    "sampleLabel": "0094_男性_青年_韩语.mp3",
    "voiceId": "s1_OYf0q7/Jj2UU2HDXqi0o5tVIo/ChmsG5FZC8LTGhnEevG4fc7LZ/",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 95,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语成熟女",
    "sampleLabel": "0095_女性_青年_韩语.mp3",
    "voiceId": "s1_FKrsc2WIx1yNh4tjRkHTQXB7GvS2PWXuhWFXUi4UQ4spDPI30WiicU4TEGrgxQ==",
    "langCode": "ko",
    "gender": "female"
  },
  {
    "index": 96,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "韩语",
    "nameZh": "韩语乐观男",
    "sampleLabel": "0096_男性_青年_韩语.mp3",
    "voiceId": "s1_GjA9qPuAHW+cZeY1Zw8NkwxRII1ssg4v7WX64EHWcGGiQDQ1EX3/bvkA+apqoA==",
    "langCode": "ko",
    "gender": "male"
  },
  {
    "index": 97,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语宁静女",
    "sampleLabel": "0097_女性_青年_西班牙语.mp3",
    "voiceId": "s1_aH2ESy5CyH0BYq0dY3MAYdDgG9arEIKZishazk/De31G8meyN5b2Y4O5mg==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 98,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语温暖伴侣",
    "sampleLabel": "0098_男性_中年_西班牙语.mp3",
    "voiceId": "s1_BZ9gNEBnQ4eTEzC1iWal+D2Cu64fSTEWxo3q9uEkTafq5T0ei0C+uSYIC6bL",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 99,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语迷人叙述",
    "sampleLabel": "0099_男性_中年_西班牙语.mp3",
    "voiceId": "s1_wBh33Z4pAFRzagEXPtNfZaRIxR8VCE3BG8tH3RY8SkuGSpRm/1r2ws8/gKZAq5XzC1u3+LWr",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 100,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语成熟叙述女",
    "sampleLabel": "0100_女性_中年_西班牙语.mp3",
    "voiceId": "s1_egipUmhIZjtgcpRAfvXDlw4eFLW2ayarhQ/jy4yTf0Tp4eULR7aR2Q==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 101,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语智慧学者",
    "sampleLabel": "0101_男性_青年_西班牙语.mp3",
    "voiceId": "s1_81sz1/ID+1ym1CVKeQxNSyLJfl3nGGvI7v/xPrkoMHpi+UuJfdT5ANRo0A==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 102,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语明亮女",
    "sampleLabel": "0102_女性_青年_西班牙语.mp3",
    "voiceId": "s1_FtJIIwKuymzjeKyviJSRUOpLpDU86bmiPgiYLhYcNLS7v9hq/+4tMLu7tX3BGSNl",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 103,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语职业女经理",
    "sampleLabel": "0103_女性_中年_西班牙语.mp3",
    "voiceId": "s1_J186KcdIuKFP7DEHZLUWJj+jC5DyF9jyIBHUWwSQeKjs2qe5y0u+R5Ii5Ll8sB3qlg==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 104,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语专横男",
    "sampleLabel": "0104_男性_青年_西班牙语.mp3",
    "voiceId": "s1_kb8XqKnL82vHMXAiWlF5aUDCtHxT1jYpD34dUNarmKsajlblXzXuBpzf7A==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 105,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语内敛男",
    "sampleLabel": "0105_男性_青年_西班牙语.mp3",
    "voiceId": "s1_VAR0LCeGrprjoWPFmuhk0SVc/u2l8NYJPPUkTYnYGI1MV3JUklWPcy0+SMncOByY",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 106,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语自信女",
    "sampleLabel": "0106_女性_青年_西班牙语.mp3",
    "voiceId": "s1_N0qI7y8XzX4opGBoUKGY5Ubp3reCCJarG7vP92eSGN7F6aW1Yug/oI2NDnqQlg==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 107,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语体贴男",
    "sampleLabel": "0107_男性_青年_西班牙语.mp3",
    "voiceId": "s1_FkXV7Qh4A91tC6sPLjqMS4knL0rdPN0cvmYS3xxF8YR5MQqV8uOos7VY5Kpr",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 108,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语坚定男",
    "sampleLabel": "0108_男性_青年_西班牙语.mp3",
    "voiceId": "s1_plwCg7GQpQJJzEgsG9pnfxs3mFhmx9Ig0LT6yWi6XNhThila78UwcnhBmmEflF7U",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 109,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语精致女",
    "sampleLabel": "0109_女性_青年_西班牙语.mp3",
    "voiceId": "s1_mDSw7V7ScMMheeF7Q7vyWd2hYnusV8qRkP6Zc1jfyzKDZRAT/5/EucGRQ/WyVA3RhA==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 110,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语理性男",
    "sampleLabel": "0110_男性_青年_西班牙语.mp3",
    "voiceId": "s1_pMnqL+eErkeP6i40kNckSA8gJx4PAp/1mSUkZ0lMnsttL5+EmTAgRo6mvQ==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 111,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语灵动女",
    "sampleLabel": "0111_女性_中年_西班牙语.mp3",
    "voiceId": "s1_CAwRfidHMJPsYciMEB5kI6dnDsSTh4QaMk5ibZ0Bd8lDO6smxwaCXnAeQfHVdQ==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 112,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语深沉男",
    "sampleLabel": "0112_男性_中年_西班牙语.mp3",
    "voiceId": "s1_AHp5esjgQmsB9Zksn1E83BWF40RfWaKRYAjXusmBM92d/lvze43g+CbI4ISR",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 113,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语挑剔女",
    "sampleLabel": "0113_女性_中年_西班牙语.mp3",
    "voiceId": "s1_n1vdr0xtoramMK6af2a1z+LrpJ5yH7dHaLeMWqi2+EoG3of1kMF+zpWqtqg=",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 114,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语真诚男",
    "sampleLabel": "0114_男性_青年_西班牙语.mp3",
    "voiceId": "s1_5/qPPzP23FlDz3ahNgMf+B0SnHWY3SKwSZbrYptunKZYAYlqnOpjo5M20g==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 115,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语坦率女",
    "sampleLabel": "0115_女性_青年_西班牙语.mp3",
    "voiceId": "s1_wL3YaWdXGxKeepuSHD2C/i+ZUcTs3Mm+gU96p/4rSmnEJS43kqc7Gds=",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 116,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语喜剧男",
    "sampleLabel": "0116_男性_青年_西班牙语.mp3",
    "voiceId": "s1_+P330wGTNojm+kdHIQRDDdzAzLSVHQkEyLlTzuL843zr0S2aiirXUw==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 117,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语强硬辩手",
    "sampleLabel": "0117_男性_中年_西班牙语.mp3",
    "voiceId": "s1_aypb9eTNBvHpID0QukP6dlU0VwD9FpyX2DYEEjz/2JaGdKROqlPd",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 118,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语强硬女boss",
    "sampleLabel": "0118_女性_中年_西班牙语.mp3",
    "voiceId": "s1_pnzT9AuyO/TP9bqWHJm0DKFx8ZZrVnaFMLwbpzfacSR7tdr1Hirinp0=",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 119,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语智慧女",
    "sampleLabel": "0119_女性_中年_西班牙语.mp3",
    "voiceId": "s1_I6r9DsmKCpyBEdBaiWemZ6mFEc7MQRiqRDCLLGNnzM4MRTA9wnx/Vg==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 120,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语稳重导师",
    "sampleLabel": "0120_男性_青年_西班牙语.mp3",
    "voiceId": "s1_HB0z9u+DnqK26CprvDMf90mrKBtzhsgagxjY0bePIXnq4SMp0Q5afOODzy4=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 121,
    "genderZh": "男性",
    "ageZh": "老年",
    "langZh": "西班牙语",
    "nameZh": "西语沙哑老男",
    "sampleLabel": "0121_男性_老年_西班牙语.mp3",
    "voiceId": "s1_TbmKkmZfEYKM9vfYQS1R24uyJltS8FuViXmGKjTmcC/dAkSlVhzPoVo=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 122,
    "genderZh": "男性",
    "ageZh": "老年",
    "langZh": "西班牙语",
    "nameZh": "西语圣诞老人",
    "sampleLabel": "0122_男性_老年_西班牙语.mp3",
    "voiceId": "s1_IkRxUAfXl0bcXJSY/V3/QNvOlZJ/8AqiA4dUDNHg/uuGCBj0MGGBEQp9",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 123,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语天真男",
    "sampleLabel": "0123_男性_青年_西班牙语.mp3",
    "voiceId": "s1_E5kHS6wTCPa6Rhn65q93fMdfhRrQnzJ3rkNq29R/BjCo9hTI8YLN",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 124,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语多变女",
    "sampleLabel": "0124_女性_青年_西班牙语.mp3",
    "voiceId": "s1_b4sQn9rLrxE4BIiXF8lRr2K7GNKeeJAUXqeXaDqNQPLIR95o9NzHCtvzHWI=",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 125,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语稳重男",
    "sampleLabel": "0125_男性_青年_西班牙语.mp3",
    "voiceId": "s1_+3pJghuqwlIWI4hdTVprlCOa6mthFeqL78VdGLasbk/6XqnCGUA=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 126,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语沙哑鬼魂",
    "sampleLabel": "0126_男性_青年_西班牙语.mp3",
    "voiceId": "s1_pdxzEElSZJ/5C8KyPHZ5NjpPdt1KlPFOOHSQ1nypsBFWdsVRTQ==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 127,
    "genderZh": "男性",
    "ageZh": "老年",
    "langZh": "西班牙语",
    "nameZh": "西语幽默老者",
    "sampleLabel": "0127_男性_老年_西班牙语.mp3",
    "voiceId": "s1_9GBmiteq/06zdPpN9xiuGRw/kMr+5Lt4hjVfiAqBrcm0/xDicGx0gmRgJm0n",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 128,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语活力男",
    "sampleLabel": "0128_男性_青年_西班牙语.mp3",
    "voiceId": "s1_oEg/pnEIXFNMf5u5uz2/T0b6zqePGcVW0LLN3j4ZjrIepaI2uQN2/GfgjUw=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 129,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语奇特女",
    "sampleLabel": "0129_女性_青年_西班牙语.mp3",
    "voiceId": "s1_FIxV802BGgsBlLN6+pJMCqwzhZ9KaTPHyplVJF1fSjpB4927TA67KljrQRvW",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 130,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语严格女boss",
    "sampleLabel": "0130_女性_青年_西班牙语.mp3",
    "voiceId": "s1_/oqOB+XlgyafJadIBa3vSOpDOyEtuPDA1zTFdP4ho0uFR8e8kJC00ciU",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 131,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语可靠男",
    "sampleLabel": "0131_男性_青年_西班牙语.mp3",
    "voiceId": "s1_hfCSvmdtWQ/h7jloohE2bvOpiL9yQtdAjc+k9Yl4dtRuX70vmiIdxjBqKA==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 132,
    "genderZh": "男性",
    "ageZh": "老年",
    "langZh": "西班牙语",
    "nameZh": "西语沉思老者",
    "sampleLabel": "0132_男性_老年_西班牙语.mp3",
    "voiceId": "s1_eaJYAFSufLLnWm0Lpxh4gFmk6EuVoq7lSUCATu1kqKTGLWOSKYmp1db+bQ==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 133,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语愤怒男",
    "sampleLabel": "0133_男性_青年_西班牙语.mp3",
    "voiceId": "s1_decO6Sf8hE0mqluommKBJXTN73o/G2CXGKF3M0qGhaLtxVv/+GGYnA==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 134,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语果断女王",
    "sampleLabel": "0134_女性_青年_西班牙语.mp3",
    "voiceId": "s1_zUN5zJ0V245wUXU7NW60ANh5IcFX+1gTaqrzd9fA/jlUGXO9K+vcFuN5WPY4jA==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 135,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语关怀女友",
    "sampleLabel": "0135_女性_青年_西班牙语.mp3",
    "voiceId": "s1_bbxZ1HIIsTG/Kr0Ba8hn9cC5pMvsDUJDyPQKVpe5YYBmQ6fI3f0AsHRZ9dWqaMsS",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 136,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语士兵男",
    "sampleLabel": "0136_男性_青年_西班牙语.mp3",
    "voiceId": "s1_1kQh9L18aS6gZK7e4WSg19sG2kPDkidApp6R2GVi/PfQU3x3HxTb9G70Ft40ISY=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 137,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语激情战士",
    "sampleLabel": "0137_男性_青年_西班牙语.mp3",
    "voiceId": "s1_Z54p7Aer+10nOY8UxScJN+PH5TQJ8gefTR/+jnX+dehcG+gb1GGCfNwj+IUJQMTsmg==",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 138,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语健谈女",
    "sampleLabel": "0138_女性_青年_西班牙语.mp3",
    "voiceId": "s1_ytJPsowO+31scZ+wRkg90LKzKYppV+Ot9w03bvdqf4iHKl7om8q+pEjy",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 139,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语深情丈夫",
    "sampleLabel": "0139_男性_中年_西班牙语.mp3",
    "voiceId": "s1_8BjewyrzNFiSjNrBBDarj0auhTbz7VDpU5dNCpEBHkjFZyYsGJGitvoY3JDGatU=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 140,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语说服力女",
    "sampleLabel": "0140_女性_青年_西班牙语.mp3",
    "voiceId": "s1_eCprxeGMUnB5x7iJd6tN/4ctNfiuxRewvlMnK5Q7+9zENjOSQ4zEdz/B4rgpdA==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 141,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "西班牙语",
    "nameZh": "西语退伍军人",
    "sampleLabel": "0141_男性_中年_西班牙语.mp3",
    "voiceId": "s1_BPNCxhTz/U7seQo7FGV6EHR9sQULbiu0KzqBWOpBxC9KeWM8ks6/wMMLyN4YuWw=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 142,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语理智经理",
    "sampleLabel": "0142_男性_青年_西班牙语.mp3",
    "voiceId": "s1_Z2HXnw23yegvNzzWIcqmGL4qKTvIrsInt9+wPYfX0BPTdHG3A7tq3XzGGjO1dts=",
    "langCode": "es",
    "gender": "male"
  },
  {
    "index": 143,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "西班牙语",
    "nameZh": "西语忧虑女",
    "sampleLabel": "0143_女性_青年_西班牙语.mp3",
    "voiceId": "s1_olojITQDiQCykdvM4wYv8RhBdztmJedZ+m2t6XjemXalCOzkfFF6Gexzx6hdtw==",
    "langCode": "es",
    "gender": "female"
  },
  {
    "index": 144,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语感性女",
    "sampleLabel": "0144_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_8JlO9KP828i8qxL9sBdQC1M11fz/pYsXVPRxHDU7BaOA31M2FhDlRX9efjjTREHU73A=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 145,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语正式男",
    "sampleLabel": "0145_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_i4K03VUWtnhbxWSyveykZYGTe6Q7sqMTKKxAJ0pK09fwBnRCVRWNyIrwdAKSJg==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 146,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语智慧女",
    "sampleLabel": "0146_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_SKKrj+oejdlwFjm7EiJ06VVCUJyrAQos2z8fqPH4a3+IW5Z5qKuL61GD3Q==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 147,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语坚定男",
    "sampleLabel": "0147_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_8eMWJ7YCj+XWPiYIEqt7u6cpUld5O4Qk00NGFnCEg2cnnZ7dVnovAfaWUPgUvuvVv452",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 148,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语低沉绅士",
    "sampleLabel": "0148_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_C4E5Nj7bzpFvOTmGcQYQeXjsFsoMIKtNOSB8y3KgUz6aVzLKHRbj01v4kgTp9ie7uLMoCmol7A==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 149,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语悲伤女",
    "sampleLabel": "0149_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_SDhFhVaA0XMISCzYZJu+w0FTm/twXf4CbYQ9aT039YOWOIiOnlmaf8K0ozs=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 150,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语激情战士",
    "sampleLabel": "0150_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_nOdjVPtEr1roN+yeLh234ktc6HBXYsI/7N445yn0EvtvSw+SINxo8q65NsREpBHcsALNMQ==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 151,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语灵动女",
    "sampleLabel": "0151_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_UM2+Ur0BSPF2ewAWuq69Z5xh7/Td91sKZPqU/ZUled+fBGipmQWwKRTMc9v7EXq8Fw==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 152,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语自信女",
    "sampleLabel": "0152_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_iNLiqrFe+qyFYYXlH98DyDgoOimfgaOnG6Q5ezbdiNDHmZ+DMrvsIlQ0ele9HdyZ5Q==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 153,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语愤怒男",
    "sampleLabel": "0153_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_Cv58rUkG9xWo9UYWt/mafKaEopluxPNOiePSgGIEpk2JJlII9fRQIsTYTA==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 154,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语迷人叙述",
    "sampleLabel": "0154_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_7c8Dqa6td5rUQJ3ayXq5bQbO+YDWg079YqihE/Q7LykJxAyK5mFRn3nPmBFd/Jm9ryPgZipwyWOS",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 155,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语严肃教父",
    "sampleLabel": "0155_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_Nd7r6pWLEzR3uPqgq1aQc8y0/293WEwiZDYuUJWdEl7dX86DqdNNWxMwob4=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 156,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语内敛男",
    "sampleLabel": "0156_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_wlce1PAxTRbBBS3WuQB/6Io6+3sam5sAobas0ZAnsQrt6578V5Leb+xb0O4oPjFntAIG",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 157,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语聪慧女",
    "sampleLabel": "0157_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_E1E3lJBGjwVtsrymZW7iL23CLf6lnIzO5jCAY1/NgSLOa0UeE3eXGbOCxTxaJiEOuw==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 158,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语善良女",
    "sampleLabel": "0158_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_EL9uSDgqGWDuVel2mQDmvfkgYx62kf06btiAhDcpRm5NdVbiwwPuMcptTKx4bHSTa45U",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 159,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语自负女",
    "sampleLabel": "0159_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_sPdsowDJDwk0cCnhBdNmmlUIk1ZS5Tp4YK6DT1gv0xNY6832J3KqqdaxZ/TD4g==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 160,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语狡黠男",
    "sampleLabel": "0160_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_qNtOu9Rm8F3SwWHcUmoGMxiw/sxet8foIKxptzkm5xL9l3hliIb1yqU=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 161,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语强硬辩手",
    "sampleLabel": "0161_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_nOMUi8+Gm4ENIRRrEy/yLOdkwY8okDh2hHznUuimu8DGiwcKomPe+9xo",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 162,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语甜美女",
    "sampleLabel": "0162_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_roC/PvYwgf4CzO8t5V5Szu4ntoYzAjbQA1Rv3m75AeeJA09NeXBlFfhOxf8=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 163,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语有魅力女",
    "sampleLabel": "0163_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_6nRFgqxU014Qlkua6ZKlYwm0WpbQp6+LRpylY6jVGIVv+YMQ9mz93xGS+ljJOiY5zw==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 164,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语温柔男",
    "sampleLabel": "0164_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_ixbEE1Dxt3YJxu7laZ4V0fQ8AxLQr/M6pRthedySOuaw5j2fuMGPcy3OAr26a8xJ",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 165,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语俏皮可爱",
    "sampleLabel": "0165_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_XBiW/XOCE91dsbrK/GIyQyOfCATS5kgs5fdAo5W5xK4rYbmYEiJwvvgwbrPYog==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 166,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语俏皮华丽",
    "sampleLabel": "0166_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_FvTt1NmH3JWMQl9PMHx43r9P0CZNnj7qICrwTAn+mPivezt1cNELeUwuZZBtI8c=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 167,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语迷人女",
    "sampleLabel": "0167_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_60x4oRJoLbPz/VMIHe5QEhFjKNlP0adCiZyfeWjmmKWk7BDKKdCj8Yjyaj1+",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 168,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语平静女",
    "sampleLabel": "0168_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_5fX07uORYBuES25dHSH48S2r4YPvHlxFOIts++ePLnzfRjRrjuNF1lkFc1U3Gg==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 169,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语沮丧男",
    "sampleLabel": "0169_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_3BqIpF/u6A+8fKH2tbceDoXk76G/jkppuJoi+vR+uijmf44JNKexKusF",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 170,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语成熟伴侣",
    "sampleLabel": "0170_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_wclc+G+Clvs0kOFG4ltBH2nL8sVtNR+xoXv3wws6cU35KSkmNl7QA4MONJ93wESP",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 171,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语喜剧男",
    "sampleLabel": "0171_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_Kr1mMLJBSEHPxlpAkZG78vLpQvusyYcINAcnLJNBp0OcqFAOR9/vVTlMCA==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 172,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语顽皮女生",
    "sampleLabel": "0172_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_Dxs53vsrV/aMfRK4yg2qThc8qWE3ZvZBAVgDr8YAAiRXChLGJp3ksVW0khcl5MkuYGiBbw==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 173,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语叙述女",
    "sampleLabel": "0173_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_nNjbaCf4NGCg+JTezjxTBYz5VpFx2AGCYVrmO0xDRFe3zIRwDFrc+iC/Bg==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 174,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语强硬女boss",
    "sampleLabel": "0174_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_ZN6Bx0EMSTiTJs8TqcoCWgmU3R31kqjwayJd/gesqg8HJ1Ir6XnWXzDfxUU=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 175,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语挑剔女",
    "sampleLabel": "0175_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_0zKLpHTjtWzioqJC2ruWcfZSc89FFZr3yjsWLx0f4WQDZWGyqFbxeYBfxhS0H1E=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 176,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语戏剧家",
    "sampleLabel": "0176_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_TgPr2P3AatFe2NeuCNZII6oF4G86QNfLBenoyc9rC8LdXjSaGslrUDaQ8mY=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 177,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语稳重导师",
    "sampleLabel": "0177_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_B4JwvMp0C/AGAjSFPfk6VDHExPkxysI5GEtW8ux2xJ2yXje4sctNUWdtgnHCNYY=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 178,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语开朗男",
    "sampleLabel": "0178_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_hlB24+kab1Tyv13tzgWCzTDQtwq3XTdMfshSvS27ZLACcAoZLWxkqQ3175c=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 179,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语魅力女王",
    "sampleLabel": "0179_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_9dxBeaoKMVVZQgefW0y04SFpNQq4KTEdN5BlziHfemCg27044nLiWoUhpOSmYWqN",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 180,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语欢乐圣诞",
    "sampleLabel": "0180_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_x4ijSDatakP+RseqYKBcudo/v82t2VlvZ6gbljDSfB/fTgGCjYsqSasTbxl/",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 181,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语天真男",
    "sampleLabel": "0181_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_N9Teredwc1dFHBy6y00RZSeIjpgc2vkmISdF9EueBmbMLZXTqFqFEpvy",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 182,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语稳重男",
    "sampleLabel": "0182_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_nwIOIZKBcrWWD6MAX9lB6jSD+08UHINTmBq8yPpzAXVIJx4gCLkD75g=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 183,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语圣诞老人",
    "sampleLabel": "0183_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_p/ri6lgzbAXhlPmFnMKNlaxzJeS2uQ0ksaRvLo3VfyaURf6WDyeZJqunpmPuI2FU",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 184,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语迷人女2",
    "sampleLabel": "0184_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_pJPjGAm4dyHBkySJkyxe8U84QEVyOWJrWue5FlPAzVVoTD7c/2lHh75xtoMVHE0=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 185,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语性感鬼魂",
    "sampleLabel": "0185_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_X/pDnbcuZsbZ2tF+iSr60fCEWJyXxgdhEY8fOHEDsetXd6IXw4LmKQ==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 186,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语滑稽长者",
    "sampleLabel": "0186_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_FQyHDe8O9/hNtUO0aUZjIL4UhNuI75XWxJVM/AV+PHbUtLEx/QqCjFq4g5poOmFs",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 187,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语冷静领导",
    "sampleLabel": "0187_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_PC8/bhakbDtE423e3RvM89oI8pG3Ykjj8OVvYGFzjCQafKSD8a+4VYmNK1B/",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 188,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语温柔教师",
    "sampleLabel": "0188_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_InMv+V6QebWjw5TvzOhUy9S9keaQQtZ1NHKcNOp22HiXMlgX8C5U7CrSC268yK+v",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 189,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语活力男",
    "sampleLabel": "0189_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_8YEYEJEcu73R+dtQxnt9sMwsZV9wK4TR6jXlhfZPmMdodrxqnONHWPr2vmwm8wE=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 190,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语可靠男",
    "sampleLabel": "0190_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_TFowFS/Ow+qmv5K89SHsnzxhLExq6HbR5bUF7z8NjAARlV7C15M0AYTjgco94A==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 191,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语深思长者",
    "sampleLabel": "0191_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_XTl9S6HsBTY2l3VRABEkSmB23zeNEWNbCXbv+0MX9fGI0BD+9ifne/xRApH1Dg==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 192,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语死神",
    "sampleLabel": "0192_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_u7Hq8DP5X+LpamfkxI7jeJkMnAudpfMKR0m783deyCMAPSa+dfPvqf5QNX/g",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 193,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语坚定女王",
    "sampleLabel": "0193_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_R4NxdcfGMDFENHaCEk8RC1QCmRAouSG141aR4d+SC31Di0soKm5zM6M4UN34khvO3g==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 194,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语奇特女",
    "sampleLabel": "0194_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_vyz3N7CdQ5GUDxMH/SuIwgNtpffrEwLz05wnmkwTcjPNp/1YNxDE2m9/xENu0qyQ",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 195,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语紧张女",
    "sampleLabel": "0195_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_JXRDKjAu0O4t7GHGdxrIz+19YaCfG/D8OAmEqdkOPML7ZNbnECPXijAEQ+LDRIY=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 196,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语友好邻居",
    "sampleLabel": "0196_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_RbUKatiIXO032WBC55y90797XLNYys8M8jAGd61IuFADJLnnadsHKAXW4pxcj9Vs+sJq",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 197,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语关怀女友",
    "sampleLabel": "0197_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_pLDXgOz5yJ/1ROIVMwqC0MvkScEaBoB+MGu86gWpp1q6K/4eCSoy2+v9IxWsERDamKlg",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 198,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语士兵男",
    "sampleLabel": "0198_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_uwpBaXGmZLEIEeBIDDfifInHC/TsB2HS8epVsVQXu64ng6btU5ZslGct/jRHNujVaQ0=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 199,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语亲切男",
    "sampleLabel": "0199_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_nmglLjFq92f/fyRHWhEeeNMDAXw4Vzg4svOYVa5nPuN1hpxC6bQ/VR0+YYGX4A+9Vw==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 200,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语深情丈夫",
    "sampleLabel": "0200_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_kpt+/wjfALvTgli00OEvW2vm6Rg+DkJ/6tvg45qEJsgXpgvhXZMKoNEnHiio8+N8TcM=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 201,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语严格女boss",
    "sampleLabel": "0201_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_/7ZCXxu6dwhK3zvvBgv+A0vieMmj9fBzVyNHQrxuAQDXLCTVH5jykU5hYr9U",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 202,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语鼓舞女",
    "sampleLabel": "0202_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_1VzGwJeJHzL40pu4wJt0lU18Jryae0Iia0PZxylTOKrS2FjVQoG8ansJBgzvIcbP",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 203,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语灵动精灵",
    "sampleLabel": "0203_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_NRjljBcnHunlsWAcRO473gkoAnzqhrc4hDEMyRs7qNwTMbkG4ayR+PVUg74MXhIv",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 204,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语戏剧优雅",
    "sampleLabel": "0204_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_k6r8J2v+wx95jOBvkBjv2rCZDw/AstRDPgkc8uobqOHJaz5E9zYaTwQfGsyOWA==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 205,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语说服力女",
    "sampleLabel": "0205_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_hIZq1NNivpTpPxT2UV8TwRwL1mXRl1IfC1rvMDQZ/aw6dOeYW7zhnw/Z8NRW+d0kZw==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 206,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语退伍军人",
    "sampleLabel": "0206_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_7CVFxnL0xJWEKfh4oC38hXPLU/pKTILwn0ogBJIWQuItkntuzf4HCUe6e1QtwLu0j3A=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 207,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语理智经理",
    "sampleLabel": "0207_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_3Inwp+JXd4+OXxP9Sq/v4daNvOc2Cx7AcG9j9Yf9iZRnMWBZuAR7pi8UBK87diDpHDU=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 208,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语忧虑女",
    "sampleLabel": "0208_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_KN9lQhWSNL2VsrB4Kca3YoV4nFrX7QqNyQf1XxWh1Pb1bXVs/t3G0ma7vJOIMESy5Q==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 209,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语生动男",
    "sampleLabel": "0209_男性_中年_葡萄牙语.mp3",
    "voiceId": "s1_vXlXHBBZzYwv/ojA1vvtZcZlsyXasC5Wig6Cj2Ucsu0y4xsTG+bqXer9N0aB+KmCXhk=",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 210,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语脆弱男",
    "sampleLabel": "0210_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_H/KcRZhzXou43DX8sJYaGVCN89PP0QqLmDxOVcoxyNnanYtrMv/G1doPJpX3",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 211,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语健谈女",
    "sampleLabel": "0211_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_bPi2wBABGm+xkMY15Wip17+W86jLwVLXtFFXMSimmUHyhtqgof1a1TDAwq/Y",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 212,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语年轻导师",
    "sampleLabel": "0212_女性_青年_葡萄牙语.mp3",
    "voiceId": "s1_E/dTirPDT+QQuWMUdUxGudLQS2+5sq+GE5J8SeAG7tlEF0PgInLtCDQEzeLAS5vhAVN2II1QlMZj7A==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 213,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语理性男",
    "sampleLabel": "0213_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_lbLo28kPu5zY31nOBYzG3y0CQTFg9/khCQ5I324+BfVmflBWUOpStHjMvnAwlA==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 214,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语智慧男",
    "sampleLabel": "0214_男性_青年_葡萄牙语.mp3",
    "voiceId": "s1_ucNxOle0mpbZH/7Rj0zy2l5swOSXL1+KpWc1Ve0Ushn9MLdL9GjFzniT0BTpFw==",
    "langCode": "pt",
    "gender": "male"
  },
  {
    "index": 215,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语激动女",
    "sampleLabel": "0215_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_G5AwWKy/lu4e7+8PiRVV9JS+kVwhZKJlfnvFfpGUemjL1QTbODQg7XclVYk=",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 216,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "葡萄牙语",
    "nameZh": "葡语果决女经理",
    "sampleLabel": "0216_女性_中年_葡萄牙语.mp3",
    "voiceId": "s1_bk7bSzMjv1t9xlwri/glY8wV3LQXPiEWoH0nWVekaDtdWMyTeAdW9TnFLm4jbM2mXxpk/g==",
    "langCode": "pt",
    "gender": "female"
  },
  {
    "index": 217,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "法语",
    "nameZh": "法语理智男",
    "sampleLabel": "0217_男性_青年_法语.mp3",
    "voiceId": "s1_1KMrOQrGC1iAc/PrOnvogilqtbPMaufWDdAUUQ0WzR1BKOrfucpmodsirXiu9g==",
    "langCode": "fr",
    "gender": "male"
  },
  {
    "index": 218,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "法语",
    "nameZh": "法语耐心主持",
    "sampleLabel": "0218_女性_青年_法语.mp3",
    "voiceId": "s1_8NObhZpZ8ZNWc70oricCBFnTdqQ2xyKYie9g8teSmlTxHL8pwnnIgksw4byqGHRL/w==",
    "langCode": "fr",
    "gender": "female"
  },
  {
    "index": 219,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "法语",
    "nameZh": "法语悠闲男",
    "sampleLabel": "0219_男性_中年_法语.mp3",
    "voiceId": "s1_6roRKVCDk9u6u1Z7rZWFG52NRSIMTSx2AYokkTTOiwtlOFHkFEGYMw==",
    "langCode": "fr",
    "gender": "male"
  },
  {
    "index": 220,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "法语",
    "nameZh": "法语电影少女",
    "sampleLabel": "0220_女性_少年_法语.mp3",
    "voiceId": "s1_AHhAY472Es5wYH0Ma+Sdn189r50Y++uPM0puB1j7wvdSFcWUxo6fZtUrBsIFpQ==",
    "langCode": "fr",
    "gender": "female"
  },
  {
    "index": 221,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "法语",
    "nameZh": "法语成熟女播",
    "sampleLabel": "0221_女性_中年_法语.mp3",
    "voiceId": "s1_x6InpFhVK/0XdB5W5a2u1XTuABa81LHzOlZup/GOLashZE3KSKSEwuKpIw==",
    "langCode": "fr",
    "gender": "female"
  },
  {
    "index": 222,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "法语",
    "nameZh": "法语叙述男",
    "sampleLabel": "0222_男性_青年_法语.mp3",
    "voiceId": "s1_KJUB8fhtXQPBBL7SRiuELX5CLGgkxnN7oAtCdHou5u1Vz3P7CZWMXuWJmw==",
    "langCode": "fr",
    "gender": "male"
  },
  {
    "index": 223,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语甜美女",
    "sampleLabel": "0223_女性_青年_印尼语.mp3",
    "voiceId": "s1_42xZezd/RaYkzvFo71bk9ukVWJnzuGsZAt6BT5ngh1DHDVYHB/UghAswvHE=",
    "langCode": "id",
    "gender": "female"
  },
  {
    "index": 224,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语冷峻男",
    "sampleLabel": "0224_男性_青年_印尼语.mp3",
    "voiceId": "s1_cuk0mnQ8qYC8bRSo8PA9etdWV+ZeTh1yILvHw7BjLDnI0ZtUq8jGzgxMXRImfCxWLNno",
    "langCode": "id",
    "gender": "male"
  },
  {
    "index": 225,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语迷人女",
    "sampleLabel": "0225_女性_青年_印尼语.mp3",
    "voiceId": "s1_NAXaW+gBczj3xwCcz3hWTtYL9yBNWiQvL15jC99h4FJzFAWr38oHyeQrNtzfK8g=",
    "langCode": "id",
    "gender": "female"
  },
  {
    "index": 226,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语宁静女",
    "sampleLabel": "0226_女性_青年_印尼语.mp3",
    "voiceId": "s1_ENp3DHlwayhVl1lLcgIbM65GRRnIXC2ekPNxab8kWQTfBQLdN5qJIyQDR54=",
    "langCode": "id",
    "gender": "female"
  },
  {
    "index": 227,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语自信女",
    "sampleLabel": "0227_女性_青年_印尼语.mp3",
    "voiceId": "s1_lhwm1zCiEUk2JQM7G/msMUQFJ8hLNWkkcrSOtowFOePd6nbCTUn8r2uEWFPoBo3WEw==",
    "langCode": "id",
    "gender": "female"
  },
  {
    "index": 228,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语关怀男",
    "sampleLabel": "0228_男性_青年_印尼语.mp3",
    "voiceId": "s1_7+KeZUqXdIaTYNVII/HFKRTr3vkuwNg2QlZJ6z7f7kIxjcjVg3r0nsCtSWk=",
    "langCode": "id",
    "gender": "male"
  },
  {
    "index": 229,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语权威男",
    "sampleLabel": "0229_男性_青年_印尼语.mp3",
    "voiceId": "s1_bv0FD0coEGt+VllMwS7exyDfLm7uwIuTYPl2jJP4R5SvaytA3q3Y4RVhj9qmlw==",
    "langCode": "id",
    "gender": "male"
  },
  {
    "index": 230,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语坚定男",
    "sampleLabel": "0230_男性_青年_印尼语.mp3",
    "voiceId": "s1_Sk0zzJSxf+vuZJpwFTen7ikdjXx1hzJylkd33hREWDKubA7OG/Ayjj9POkcs3ZtQ",
    "langCode": "id",
    "gender": "male"
  },
  {
    "index": 231,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "印尼语",
    "nameZh": "印尼语柔和女",
    "sampleLabel": "0231_女性_青年_印尼语.mp3",
    "voiceId": "s1_zguGHJJttiK35CruUDmH+QH+j3RMqM+kCoOb2WwGLcZW0gt1YJjafsqP+Aro",
    "langCode": "id",
    "gender": "female"
  },
  {
    "index": 232,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "德语",
    "nameZh": "德语真诚男",
    "sampleLabel": "0232_男性_中年_德语.mp3",
    "voiceId": "s1_ytAc8ro9zyaJw3jE/xQ+hi2fxGLMp/JN/t4W5sTegVeSkNlet122O2ux",
    "langCode": "de",
    "gender": "male"
  },
  {
    "index": 233,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "德语",
    "nameZh": "德语灵动女",
    "sampleLabel": "0233_女性_青年_德语.mp3",
    "voiceId": "s1_8HOEAjD2yXO+3T5HV76rymObrOTZnpQknbC7TPJNv4neEVCv74RNGg==",
    "langCode": "de",
    "gender": "female"
  },
  {
    "index": 234,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "德语",
    "nameZh": "德语活泼男",
    "sampleLabel": "0234_男性_青年_德语.mp3",
    "voiceId": "s1_wc51aBb22bVxuYKro6x0ElwLvuoZP8xn3zlgcJxSfM1L1T2W1U4HoDs=",
    "langCode": "de",
    "gender": "male"
  },
  {
    "index": 235,
    "genderZh": "女性",
    "ageZh": "少年",
    "langZh": "俄语",
    "nameZh": "俄语青梅竹马",
    "sampleLabel": "0235_女性_少年_俄语.mp3",
    "voiceId": "s1_/SoDTv9nR0I8dmOB887qICo3L8hVuwu4BQxRbn7WetHa0zTfqiellhmkQAX0VNFK5wYoTuuR8g==",
    "langCode": "ru",
    "gender": "female"
  },
  {
    "index": 236,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "俄语",
    "nameZh": "俄语傲慢女王",
    "sampleLabel": "0236_女性_青年_俄语.mp3",
    "voiceId": "s1_bRjEDDJQ69We9ZrbfB2FFM8mylK+brAiIZLUCxdChrN82ZwAR/hzI7ar7MqW",
    "langCode": "ru",
    "gender": "female"
  },
  {
    "index": 237,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "俄语",
    "nameZh": "俄语雄心女",
    "sampleLabel": "0237_女性_青年_俄语.mp3",
    "voiceId": "s1_qboSbxU2siSnx5F97C0NPcS7wTfMy1IlNCPV8ZT7EtFwRO+d1VjWncXHkjMbyA==",
    "langCode": "ru",
    "gender": "female"
  },
  {
    "index": 238,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "俄语",
    "nameZh": "俄语稳重男",
    "sampleLabel": "0238_男性_中年_俄语.mp3",
    "voiceId": "s1_znlThmh6j6q9oa05Je8N3Me9VDc6pG9iW9McOk7LBwBBoV7tZkIIWnwo9A==",
    "langCode": "ru",
    "gender": "male"
  },
  {
    "index": 239,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "俄语",
    "nameZh": "俄语疯狂女",
    "sampleLabel": "0239_女性_青年_俄语.mp3",
    "voiceId": "s1_M0wyjMMbHZngUdxH6EOejqymg6xtB0CNyz4mwRyG2SFVCxnnAi8Luyre",
    "langCode": "ru",
    "gender": "female"
  },
  {
    "index": 240,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "俄语",
    "nameZh": "俄语同情女",
    "sampleLabel": "0240_女性_青年_俄语.mp3",
    "voiceId": "s1_8Pcx/xrNMW8n5usMChdFX+Rqf6UYkNcFVnxrlcjzwPoHtA5PYavmMgp2ca2F9wI=",
    "langCode": "ru",
    "gender": "female"
  },
  {
    "index": 241,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "俄语",
    "nameZh": "俄语磁性男",
    "sampleLabel": "0241_男性_青年_俄语.mp3",
    "voiceId": "s1_7KUU3dp1HM/IMg/P4xXn1vn6NasZmTnkJL/zyBETrPuJP2Ii0nHq2j6MKoI2",
    "langCode": "ru",
    "gender": "male"
  },
  {
    "index": 242,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "俄语",
    "nameZh": "俄语暴躁男",
    "sampleLabel": "0242_男性_青年_俄语.mp3",
    "voiceId": "s1_iWQG6Jka+V3OY3aoR5qjr/tnTU7m4VU0fqfQYQMeeT36t2whPBt+fFjC8HrsNCQ=",
    "langCode": "ru",
    "gender": "male"
  },
  {
    "index": 243,
    "genderZh": "女性",
    "ageZh": "中年",
    "langZh": "意大利语",
    "nameZh": "意语勇敢女英雄",
    "sampleLabel": "0243_女性_中年_意大利语.mp3",
    "voiceId": "s1_qF69h6CyxxCE7cGATAB7jVIm+A9MqPkhddKVMoEzvSehSMFtpV5KcYkfgSs=",
    "langCode": "it",
    "gender": "female"
  },
  {
    "index": 244,
    "genderZh": "男性",
    "ageZh": "中年",
    "langZh": "意大利语",
    "nameZh": "意语叙述男",
    "sampleLabel": "0244_男性_中年_意大利语.mp3",
    "voiceId": "s1_+hrw6tqUlN86bWPJ25X5haHwc+1bQkr6xmJeWpm5rSkjFemghfCe7g==",
    "langCode": "it",
    "gender": "male"
  },
  {
    "index": 245,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "意大利语",
    "nameZh": "意语流浪巫师",
    "sampleLabel": "0245_女性_青年_意大利语.mp3",
    "voiceId": "s1_6+WhHdDJZho0NkW50fqDL0Z8f8A8XS4+G8uqWAyyNmSfO24zUO270JC+rBEV3mccfQ==",
    "langCode": "it",
    "gender": "female"
  },
  {
    "index": 246,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "意大利语",
    "nameZh": "意语冷静女领",
    "sampleLabel": "0246_女性_青年_意大利语.mp3",
    "voiceId": "s1_3BGnj3Cqyf7XHhMRlpn8/r24L4+YZ184qUQKxB6us28QW+muFRo91hO3Hjw+yg==",
    "langCode": "it",
    "gender": "female"
  },
  {
    "index": 247,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "阿拉伯语",
    "nameZh": "阿语宁静女",
    "sampleLabel": "0247_女性_青年_阿拉伯语.mp3",
    "voiceId": "s1_cvt8+rCid412IjeAdG3RgD8tr7qmkDeookcebtQ67y7xB7t4SHYWWA==",
    "langCode": "ar",
    "gender": "female"
  },
  {
    "index": 248,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "阿拉伯语",
    "nameZh": "阿语友好男",
    "sampleLabel": "0248_男性_青年_阿拉伯语.mp3",
    "voiceId": "s1_SWKqdI3ZxTvXtILL3OR6sWyN13UgniH5tnnMtNqOG71LOjJlHJUe2khI",
    "langCode": "ar",
    "gender": "male"
  },
  {
    "index": 249,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "土耳其语",
    "nameZh": "土语宁静女",
    "sampleLabel": "0249_女性_青年_土耳其语.mp3",
    "voiceId": "s1_l9GyTrhQP2109w8//bKCNBOFNQv9eHNO7LrctvstAxefQFU9CK6RLtY=",
    "langCode": "tr",
    "gender": "female"
  },
  {
    "index": 250,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "土耳其语",
    "nameZh": "土语磁性男",
    "sampleLabel": "0250_男性_青年_土耳其语.mp3",
    "voiceId": "s1_oVikFONFwbbw08cRng3rt4EoOHlu8Lk5LScXOKcISubL/MOM9X0ZGi06r4Fcbg==",
    "langCode": "tr",
    "gender": "male"
  },
  {
    "index": 251,
    "genderZh": "女性",
    "ageZh": "青年",
    "langZh": "乌克兰语",
    "nameZh": "乌语宁静女",
    "sampleLabel": "0251_女性_青年_乌克兰语.mp3",
    "voiceId": "s1_8NyGeQCA140PKJMPG4KAEA05o7bbV4eOfVCaoV1iZh8eEFTSg9SkqxtXCA==",
    "langCode": "uk",
    "gender": "female"
  },
  {
    "index": 252,
    "genderZh": "男性",
    "ageZh": "青年",
    "langZh": "乌克兰语",
    "nameZh": "乌语智慧男",
    "sampleLabel": "0252_男性_青年_乌克兰语.mp3",
    "voiceId": "s1_grPSlL482n7qa1F/jQy8ZE78hHue0QPYljSSgBjy80QqZifYsja1QXUmxBIy",
    "langCode": "uk",
    "gender": "male"
  }
];
